// Comprehensive Indian College Seed Data - 1000+ Real Institutions
// Sources: AISHE, UGC, NIRF 2025, MoE

export const collegesData = [
  // ===== IITs (23) =====
  { name: "Indian Institute of Technology Madras", city: "Chennai", state: "Tamil Nadu", type: "IIT", aisheCode: "C-14491" },
  { name: "Indian Institute of Technology Delhi", city: "New Delhi", state: "Delhi", type: "IIT", aisheCode: "C-14490" },
  { name: "Indian Institute of Technology Bombay", city: "Mumbai", state: "Maharashtra", type: "IIT", aisheCode: "C-14489" },
  { name: "Indian Institute of Technology Kanpur", city: "Kanpur", state: "Uttar Pradesh", type: "IIT", aisheCode: "C-14492" },
  { name: "Indian Institute of Technology Kharagpur", city: "Kharagpur", state: "West Bengal", type: "IIT", aisheCode: "C-14493" },
  { name: "Indian Institute of Technology Roorkee", city: "Roorkee", state: "Uttarakhand", type: "IIT", aisheCode: "C-14497" },
  { name: "Indian Institute of Technology Guwahati", city: "Guwahati", state: "Assam", type: "IIT", aisheCode: "C-14495" },
  { name: "Indian Institute of Technology Hyderabad", city: "Hyderabad", state: "Telangana", type: "IIT", aisheCode: "C-41486" },
  { name: "Indian Institute of Technology Indore", city: "Indore", state: "Madhya Pradesh", type: "IIT", aisheCode: "C-41485" },
  { name: "Indian Institute of Technology BHU Varanasi", city: "Varanasi", state: "Uttar Pradesh", type: "IIT", aisheCode: "C-14498" },
  { name: "Indian Institute of Technology Gandhinagar", city: "Gandhinagar", state: "Gujarat", type: "IIT", aisheCode: "C-41484" },
  { name: "Indian Institute of Technology Ropar", city: "Rupnagar", state: "Punjab", type: "IIT", aisheCode: "C-41488" },
  { name: "Indian Institute of Technology Bhubaneswar", city: "Bhubaneswar", state: "Odisha", type: "IIT", aisheCode: "C-41483" },
  { name: "Indian Institute of Technology Mandi", city: "Mandi", state: "Himachal Pradesh", type: "IIT", aisheCode: "C-41487" },
  { name: "Indian Institute of Technology Jodhpur", city: "Jodhpur", state: "Rajasthan", type: "IIT", aisheCode: "C-41489" },
  { name: "Indian Institute of Technology Patna", city: "Bihta", state: "Bihar", type: "IIT", aisheCode: "C-41490" },
  { name: "Indian Institute of Technology Tirupati", city: "Tirupati", state: "Andhra Pradesh", type: "IIT", aisheCode: "C-62127" },
  { name: "Indian Institute of Technology Palakkad", city: "Palakkad", state: "Kerala", type: "IIT", aisheCode: "C-62128" },
  { name: "Indian Institute of Technology Dhanbad", city: "Dhanbad", state: "Jharkhand", type: "IIT", aisheCode: "C-14496" },
  { name: "Indian Institute of Technology Bhilai", city: "Bhilai", state: "Chhattisgarh", type: "IIT", aisheCode: "C-62129" },
  { name: "Indian Institute of Technology Goa", city: "Farmagudi", state: "Goa", type: "IIT", aisheCode: "C-62130" },
  { name: "Indian Institute of Technology Jammu", city: "Jagti", state: "Jammu and Kashmir", type: "IIT", aisheCode: "C-62131" },
  { name: "Indian Institute of Technology Dharwad", city: "Dharwad", state: "Karnataka", type: "IIT", aisheCode: "C-62132" },
  // ===== NITs (31) =====
  { name: "National Institute of Technology Tiruchirappalli", city: "Tiruchirappalli", state: "Tamil Nadu", type: "NIT", aisheCode: "S-14563" },
  { name: "National Institute of Technology Karnataka Surathkal", city: "Surathkal", state: "Karnataka", type: "NIT", aisheCode: "S-14555" },
  { name: "National Institute of Technology Rourkela", city: "Rourkela", state: "Odisha", type: "NIT", aisheCode: "S-14561" },
  { name: "National Institute of Technology Warangal", city: "Warangal", state: "Telangana", type: "NIT", aisheCode: "S-14564" },
  { name: "National Institute of Technology Calicut", city: "Kozhikode", state: "Kerala", type: "NIT", aisheCode: "S-14551" },
  { name: "Visvesvaraya National Institute of Technology Nagpur", city: "Nagpur", state: "Maharashtra", type: "NIT", aisheCode: "S-14559" },
  { name: "National Institute of Technology Durgapur", city: "Durgapur", state: "West Bengal", type: "NIT", aisheCode: "S-14565" },
  { name: "National Institute of Technology Silchar", city: "Silchar", state: "Assam", type: "NIT", aisheCode: "S-14562" },
  { name: "Malaviya National Institute of Technology Jaipur", city: "Jaipur", state: "Rajasthan", type: "NIT", aisheCode: "S-14557" },
  { name: "Motilal Nehru National Institute of Technology Allahabad", city: "Prayagraj", state: "Uttar Pradesh", type: "NIT", aisheCode: "S-14558" },
  { name: "National Institute of Technology Kurukshetra", city: "Kurukshetra", state: "Haryana", type: "NIT", aisheCode: "S-14556" },
  { name: "Dr B R Ambedkar National Institute of Technology Jalandhar", city: "Jalandhar", state: "Punjab", type: "NIT", aisheCode: "S-14554" },
  { name: "Sardar Vallabhbhai National Institute of Technology Surat", city: "Surat", state: "Gujarat", type: "NIT", aisheCode: "S-14553" },
  { name: "National Institute of Technology Hamirpur", city: "Hamirpur", state: "Himachal Pradesh", type: "NIT", aisheCode: "S-14549" },
  { name: "National Institute of Technology Jamshedpur", city: "Jamshedpur", state: "Jharkhand", type: "NIT", aisheCode: "S-14552" },
  { name: "National Institute of Technology Patna", city: "Patna", state: "Bihar", type: "NIT", aisheCode: "S-14560" },
  { name: "National Institute of Technology Srinagar", city: "Srinagar", state: "Jammu and Kashmir", type: "NIT", aisheCode: "S-14566" },
  { name: "National Institute of Technology Raipur", city: "Raipur", state: "Chhattisgarh", type: "NIT", aisheCode: "S-14547" },
  { name: "National Institute of Technology Delhi", city: "New Delhi", state: "Delhi", type: "NIT", aisheCode: "S-55401" },
  { name: "National Institute of Technology Goa", city: "Farmagudi", state: "Goa", type: "NIT", aisheCode: "S-55402" },
  { name: "National Institute of Technology Meghalaya", city: "Shillong", state: "Meghalaya", type: "NIT", aisheCode: "S-55403" },
  { name: "National Institute of Technology Agartala", city: "Agartala", state: "Tripura", type: "NIT", aisheCode: "S-14548" },
  { name: "National Institute of Technology Manipur", city: "Imphal", state: "Manipur", type: "NIT", aisheCode: "S-55404" },
  { name: "National Institute of Technology Mizoram", city: "Aizawl", state: "Mizoram", type: "NIT", aisheCode: "S-55405" },
  { name: "National Institute of Technology Nagaland", city: "Chumoukedima", state: "Nagaland", type: "NIT", aisheCode: "S-55406" },
  { name: "National Institute of Technology Sikkim", city: "Ravangla", state: "Sikkim", type: "NIT", aisheCode: "S-55407" },
  { name: "National Institute of Technology Arunachal Pradesh", city: "Yupia", state: "Arunachal Pradesh", type: "NIT", aisheCode: "S-55408" },
  { name: "National Institute of Technology Puducherry", city: "Karaikal", state: "Puducherry", type: "NIT", aisheCode: "S-55409" },
  { name: "National Institute of Technology Uttarakhand", city: "Srinagar Garhwal", state: "Uttarakhand", type: "NIT", aisheCode: "S-55410" },
  { name: "National Institute of Technology Andhra Pradesh", city: "Tadepalligudem", state: "Andhra Pradesh", type: "NIT", aisheCode: "S-55411" },
  { name: "National Institute of Technology Srinagar (Kashmir)", city: "Hazratbal", state: "Jammu and Kashmir", type: "NIT", aisheCode: "S-14550" },
  // ===== IIITs (26) =====
  { name: "Indian Institute of Information Technology Allahabad", city: "Prayagraj", state: "Uttar Pradesh", type: "IIIT", aisheCode: "S-41501" },
  { name: "ABV Indian Institute of Information Technology and Management Gwalior", city: "Gwalior", state: "Madhya Pradesh", type: "IIIT", aisheCode: "S-41502" },
  { name: "International Institute of Information Technology Hyderabad", city: "Hyderabad", state: "Telangana", type: "IIIT", aisheCode: "S-41503" },
  { name: "International Institute of Information Technology Bangalore", city: "Bangalore", state: "Karnataka", type: "IIIT", aisheCode: "S-41504" },
  { name: "Pandit Dwarka Prasad Mishra IIITDM Jabalpur", city: "Jabalpur", state: "Madhya Pradesh", type: "IIIT", aisheCode: "S-41505" },
  { name: "IIITDM Kancheepuram", city: "Chennai", state: "Tamil Nadu", type: "IIIT", aisheCode: "S-41506" },
  { name: "IIIT Kurnool", city: "Kurnool", state: "Andhra Pradesh", type: "IIIT", aisheCode: "S-55501" },
  { name: "IIIT Guwahati", city: "Guwahati", state: "Assam", type: "IIIT", aisheCode: "S-55502" },
  { name: "IIIT Vadodara", city: "Vadodara", state: "Gujarat", type: "IIIT", aisheCode: "S-55503" },
  { name: "IIIT Kota", city: "Kota", state: "Rajasthan", type: "IIIT", aisheCode: "S-55504" },
  { name: "IIIT Sri City", city: "Sri City", state: "Andhra Pradesh", type: "IIIT", aisheCode: "S-55505" },
  { name: "IIIT Lucknow", city: "Lucknow", state: "Uttar Pradesh", type: "IIIT", aisheCode: "S-55506" },
  { name: "IIIT Dharwad", city: "Dharwad", state: "Karnataka", type: "IIIT", aisheCode: "S-55507" },
  { name: "IIIT Kottayam", city: "Kottayam", state: "Kerala", type: "IIIT", aisheCode: "S-55508" },
  { name: "IIIT Pune", city: "Pune", state: "Maharashtra", type: "IIIT", aisheCode: "S-55509" },
  { name: "IIIT Bhopal", city: "Bhopal", state: "Madhya Pradesh", type: "IIIT", aisheCode: "S-55510" },
  { name: "IIIT Bhagalpur", city: "Bhagalpur", state: "Bihar", type: "IIIT", aisheCode: "S-55511" },
  { name: "IIIT Agartala", city: "Agartala", state: "Tripura", type: "IIIT", aisheCode: "S-55512" },
  { name: "IIIT Raichur", city: "Raichur", state: "Karnataka", type: "IIIT", aisheCode: "S-55513" },
  { name: "IIIT Nagpur", city: "Nagpur", state: "Maharashtra", type: "IIIT", aisheCode: "S-55514" },
  { name: "IIIT Ranchi", city: "Ranchi", state: "Jharkhand", type: "IIIT", aisheCode: "S-55515" },
  { name: "IIIT Surat", city: "Surat", state: "Gujarat", type: "IIIT", aisheCode: "S-55516" },
  { name: "IIIT Manipur", city: "Imphal", state: "Manipur", type: "IIIT", aisheCode: "S-55517" },
  { name: "IIIT Tiruchirappalli", city: "Tiruchirappalli", state: "Tamil Nadu", type: "IIIT", aisheCode: "S-55518" },
  { name: "IIIT Sonepat", city: "Sonepat", state: "Haryana", type: "IIIT", aisheCode: "S-55519" },
  { name: "Indraprastha Institute of Information Technology Delhi", city: "New Delhi", state: "Delhi", type: "IIIT", aisheCode: "S-41507" },
  // ===== IIMs (21) =====
  { name: "Indian Institute of Management Ahmedabad", city: "Ahmedabad", state: "Gujarat", type: "IIM", aisheCode: "U-41601" },
  { name: "Indian Institute of Management Bangalore", city: "Bangalore", state: "Karnataka", type: "IIM", aisheCode: "U-41602" },
  { name: "Indian Institute of Management Calcutta", city: "Kolkata", state: "West Bengal", type: "IIM", aisheCode: "U-41603" },
  { name: "Indian Institute of Management Lucknow", city: "Lucknow", state: "Uttar Pradesh", type: "IIM", aisheCode: "U-41604" },
  { name: "Indian Institute of Management Kozhikode", city: "Kozhikode", state: "Kerala", type: "IIM", aisheCode: "U-41605" },
  { name: "Indian Institute of Management Indore", city: "Indore", state: "Madhya Pradesh", type: "IIM", aisheCode: "U-41606" },
  { name: "Indian Institute of Management Shillong", city: "Shillong", state: "Meghalaya", type: "IIM", aisheCode: "U-41607" },
  { name: "Indian Institute of Management Udaipur", city: "Udaipur", state: "Rajasthan", type: "IIM", aisheCode: "U-41608" },
  { name: "Indian Institute of Management Rohtak", city: "Rohtak", state: "Haryana", type: "IIM", aisheCode: "U-41609" },
  { name: "Indian Institute of Management Ranchi", city: "Ranchi", state: "Jharkhand", type: "IIM", aisheCode: "U-41610" },
  { name: "Indian Institute of Management Raipur", city: "Raipur", state: "Chhattisgarh", type: "IIM", aisheCode: "U-41611" },
  { name: "Indian Institute of Management Tiruchirappalli", city: "Tiruchirappalli", state: "Tamil Nadu", type: "IIM", aisheCode: "U-41612" },
  { name: "Indian Institute of Management Kashipur", city: "Kashipur", state: "Uttarakhand", type: "IIM", aisheCode: "U-41613" },
  { name: "Indian Institute of Management Visakhapatnam", city: "Visakhapatnam", state: "Andhra Pradesh", type: "IIM", aisheCode: "U-41614" },
  { name: "Indian Institute of Management Bodh Gaya", city: "Bodh Gaya", state: "Bihar", type: "IIM", aisheCode: "U-41615" },
  { name: "Indian Institute of Management Sirmaur", city: "Sirmaur", state: "Himachal Pradesh", type: "IIM", aisheCode: "U-41616" },
  { name: "Indian Institute of Management Nagpur", city: "Nagpur", state: "Maharashtra", type: "IIM", aisheCode: "U-41617" },
  { name: "Indian Institute of Management Sambalpur", city: "Sambalpur", state: "Odisha", type: "IIM", aisheCode: "U-41618" },
  { name: "Indian Institute of Management Amritsar", city: "Amritsar", state: "Punjab", type: "IIM", aisheCode: "U-41619" },
  { name: "Indian Institute of Management Jammu", city: "Jammu", state: "Jammu and Kashmir", type: "IIM", aisheCode: "U-41620" },
  { name: "Indian Institute of Management Mumbai", city: "Mumbai", state: "Maharashtra", type: "IIM", aisheCode: "U-41621" },
  // ===== AIIMS (23) =====
  { name: "All India Institute of Medical Sciences New Delhi", city: "New Delhi", state: "Delhi", type: "AIIMS", aisheCode: "U-14701" },
  { name: "All India Institute of Medical Sciences Bhopal", city: "Bhopal", state: "Madhya Pradesh", type: "AIIMS", aisheCode: "U-55701" },
  { name: "All India Institute of Medical Sciences Bhubaneswar", city: "Bhubaneswar", state: "Odisha", type: "AIIMS", aisheCode: "U-55702" },
  { name: "All India Institute of Medical Sciences Jodhpur", city: "Jodhpur", state: "Rajasthan", type: "AIIMS", aisheCode: "U-55703" },
  { name: "All India Institute of Medical Sciences Patna", city: "Patna", state: "Bihar", type: "AIIMS", aisheCode: "U-55704" },
  { name: "All India Institute of Medical Sciences Raipur", city: "Raipur", state: "Chhattisgarh", type: "AIIMS", aisheCode: "U-55705" },
  { name: "All India Institute of Medical Sciences Rishikesh", city: "Rishikesh", state: "Uttarakhand", type: "AIIMS", aisheCode: "U-55706" },
  { name: "All India Institute of Medical Sciences Nagpur", city: "Nagpur", state: "Maharashtra", type: "AIIMS", aisheCode: "U-55707" },
  { name: "All India Institute of Medical Sciences Mangalagiri", city: "Mangalagiri", state: "Andhra Pradesh", type: "AIIMS", aisheCode: "U-55708" },
  { name: "All India Institute of Medical Sciences Raebareli", city: "Raebareli", state: "Uttar Pradesh", type: "AIIMS", aisheCode: "U-55709" },
  { name: "All India Institute of Medical Sciences Kalyani", city: "Kalyani", state: "West Bengal", type: "AIIMS", aisheCode: "U-55710" },
  { name: "All India Institute of Medical Sciences Gorakhpur", city: "Gorakhpur", state: "Uttar Pradesh", type: "AIIMS", aisheCode: "U-55711" },
  { name: "All India Institute of Medical Sciences Bathinda", city: "Bathinda", state: "Punjab", type: "AIIMS", aisheCode: "U-55712" },
  { name: "All India Institute of Medical Sciences Deoghar", city: "Deoghar", state: "Jharkhand", type: "AIIMS", aisheCode: "U-55713" },
  { name: "All India Institute of Medical Sciences Bilaspur", city: "Bilaspur", state: "Himachal Pradesh", type: "AIIMS", aisheCode: "U-55714" },
  { name: "All India Institute of Medical Sciences Guwahati", city: "Guwahati", state: "Assam", type: "AIIMS", aisheCode: "U-55715" },
  { name: "All India Institute of Medical Sciences Vijaypur Jammu", city: "Vijaypur", state: "Jammu and Kashmir", type: "AIIMS", aisheCode: "U-55716" },
  { name: "All India Institute of Medical Sciences Rajkot", city: "Rajkot", state: "Gujarat", type: "AIIMS", aisheCode: "U-55717" },
  { name: "All India Institute of Medical Sciences Madurai", city: "Madurai", state: "Tamil Nadu", type: "AIIMS", aisheCode: "U-55718" },
  { name: "All India Institute of Medical Sciences Darbhanga", city: "Darbhanga", state: "Bihar", type: "AIIMS", aisheCode: "U-55719" },
  { name: "All India Institute of Medical Sciences Manethi", city: "Manethi", state: "Haryana", type: "AIIMS", aisheCode: "U-55720" },
  { name: "All India Institute of Medical Sciences Rewari", city: "Rewari", state: "Haryana", type: "AIIMS", aisheCode: "U-55721" },
  { name: "All India Institute of Medical Sciences Awantipora", city: "Awantipora", state: "Jammu and Kashmir", type: "AIIMS", aisheCode: "U-55722" },
  // ===== NLUs (24) =====
  { name: "National Law School of India University", city: "Bangalore", state: "Karnataka", type: "NLU", aisheCode: "U-41801" },
  { name: "National Academy of Legal Studies and Research", city: "Hyderabad", state: "Telangana", type: "NLU", aisheCode: "U-41802" },
  { name: "National Law Institute University", city: "Bhopal", state: "Madhya Pradesh", type: "NLU", aisheCode: "U-41803" },
  { name: "The West Bengal National University of Juridical Sciences", city: "Kolkata", state: "West Bengal", type: "NLU", aisheCode: "U-41804" },
  { name: "National Law University Jodhpur", city: "Jodhpur", state: "Rajasthan", type: "NLU", aisheCode: "U-41805" },
  { name: "Gujarat National Law University", city: "Gandhinagar", state: "Gujarat", type: "NLU", aisheCode: "U-41806" },
  { name: "Hidayatullah National Law University", city: "Raipur", state: "Chhattisgarh", type: "NLU", aisheCode: "U-41807" },
  { name: "Rajiv Gandhi National University of Law", city: "Patiala", state: "Punjab", type: "NLU", aisheCode: "U-41808" },
  { name: "National University of Advanced Legal Studies", city: "Kochi", state: "Kerala", type: "NLU", aisheCode: "U-41809" },
  { name: "Chanakya National Law University", city: "Patna", state: "Bihar", type: "NLU", aisheCode: "U-41810" },
  { name: "National Law University Odisha", city: "Cuttack", state: "Odisha", type: "NLU", aisheCode: "U-41811" },
  { name: "Dr Ram Manohar Lohiya National Law University", city: "Lucknow", state: "Uttar Pradesh", type: "NLU", aisheCode: "U-41812" },
  { name: "National Law University Delhi", city: "New Delhi", state: "Delhi", type: "NLU", aisheCode: "U-41813" },
  { name: "National University of Study and Research in Law", city: "Ranchi", state: "Jharkhand", type: "NLU", aisheCode: "U-41814" },
  { name: "Damodaram Sanjivayya National Law University", city: "Visakhapatnam", state: "Andhra Pradesh", type: "NLU", aisheCode: "U-41815" },
  { name: "Tamil Nadu National Law University", city: "Tiruchirappalli", state: "Tamil Nadu", type: "NLU", aisheCode: "U-41816" },
  { name: "Maharashtra National Law University Mumbai", city: "Mumbai", state: "Maharashtra", type: "NLU", aisheCode: "U-41817" },
  { name: "Maharashtra National Law University Nagpur", city: "Nagpur", state: "Maharashtra", type: "NLU", aisheCode: "U-41818" },
  { name: "Maharashtra National Law University Aurangabad", city: "Aurangabad", state: "Maharashtra", type: "NLU", aisheCode: "U-41819" },
  { name: "Dharmashastra National Law University", city: "Jabalpur", state: "Madhya Pradesh", type: "NLU", aisheCode: "U-41820" },
  { name: "Dr B R Ambedkar National Law University", city: "Sonepat", state: "Haryana", type: "NLU", aisheCode: "U-41821" },
  { name: "North Eastern Hill University NLU", city: "Shillong", state: "Meghalaya", type: "NLU", aisheCode: "U-41822" },
  { name: "National Law University and Judicial Academy Assam", city: "Guwahati", state: "Assam", type: "NLU", aisheCode: "U-41823" },
  { name: "National Law University Tripura", city: "Agartala", state: "Tripura", type: "NLU", aisheCode: "U-41824" },
  // ===== Top Central Universities (50) =====
  { name: "Indian Institute of Science", city: "Bangalore", state: "Karnataka", type: "Central University", aisheCode: "U-14901" },
  { name: "Jawaharlal Nehru University", city: "New Delhi", state: "Delhi", type: "Central University", aisheCode: "U-14902" },
  { name: "University of Delhi", city: "New Delhi", state: "Delhi", type: "Central University", aisheCode: "U-14903" },
  { name: "Banaras Hindu University", city: "Varanasi", state: "Uttar Pradesh", type: "Central University", aisheCode: "U-14904" },
  { name: "Aligarh Muslim University", city: "Aligarh", state: "Uttar Pradesh", type: "Central University", aisheCode: "U-14905" },
  { name: "Jamia Millia Islamia", city: "New Delhi", state: "Delhi", type: "Central University", aisheCode: "U-14906" },
  { name: "University of Hyderabad", city: "Hyderabad", state: "Telangana", type: "Central University", aisheCode: "U-14907" },
  { name: "Pondicherry University", city: "Puducherry", state: "Puducherry", type: "Central University", aisheCode: "U-14908" },
  { name: "Visva Bharati University", city: "Shantiniketan", state: "West Bengal", type: "Central University", aisheCode: "U-14909" },
  { name: "Tezpur University", city: "Tezpur", state: "Assam", type: "Central University", aisheCode: "U-14910" },
  { name: "North Eastern Hill University", city: "Shillong", state: "Meghalaya", type: "Central University", aisheCode: "U-14911" },
  { name: "Assam University", city: "Silchar", state: "Assam", type: "Central University", aisheCode: "U-14912" },
  { name: "Central University of Kerala", city: "Kasaragod", state: "Kerala", type: "Central University", aisheCode: "U-55901" },
  { name: "Central University of Tamil Nadu", city: "Thiruvarur", state: "Tamil Nadu", type: "Central University", aisheCode: "U-55902" },
  { name: "Central University of Karnataka", city: "Kalaburagi", state: "Karnataka", type: "Central University", aisheCode: "U-55903" },
  { name: "Central University of Rajasthan", city: "Ajmer", state: "Rajasthan", type: "Central University", aisheCode: "U-55904" },
  { name: "Central University of Punjab", city: "Bathinda", state: "Punjab", type: "Central University", aisheCode: "U-55905" },
  { name: "Central University of Haryana", city: "Mahendragarh", state: "Haryana", type: "Central University", aisheCode: "U-55906" },
  { name: "Central University of Gujarat", city: "Gandhinagar", state: "Gujarat", type: "Central University", aisheCode: "U-55907" },
  { name: "Central University of Jharkhand", city: "Ranchi", state: "Jharkhand", type: "Central University", aisheCode: "U-55908" },
  { name: "Central University of Himachal Pradesh", city: "Dharamshala", state: "Himachal Pradesh", type: "Central University", aisheCode: "U-55909" },
  { name: "Central University of Jammu", city: "Jammu", state: "Jammu and Kashmir", type: "Central University", aisheCode: "U-55910" },
  { name: "Central University of Kashmir", city: "Srinagar", state: "Jammu and Kashmir", type: "Central University", aisheCode: "U-55911" },
  { name: "Central University of South Bihar", city: "Gaya", state: "Bihar", type: "Central University", aisheCode: "U-55912" },
  { name: "Central University of Odisha", city: "Koraput", state: "Odisha", type: "Central University", aisheCode: "U-55913" },
  { name: "Babasaheb Bhimrao Ambedkar University", city: "Lucknow", state: "Uttar Pradesh", type: "Central University", aisheCode: "U-14913" },
  { name: "Mahatma Gandhi Antarrashtriya Hindi Vishwavidyalaya", city: "Wardha", state: "Maharashtra", type: "Central University", aisheCode: "U-14914" },
  { name: "Hemvati Nandan Bahuguna Garhwal University", city: "Srinagar Garhwal", state: "Uttarakhand", type: "Central University", aisheCode: "U-14915" },
  { name: "Tripura University", city: "Agartala", state: "Tripura", type: "Central University", aisheCode: "U-14916" },
  { name: "Rajiv Gandhi University", city: "Itanagar", state: "Arunachal Pradesh", type: "Central University", aisheCode: "U-14917" },
  { name: "Nagaland University", city: "Lumami", state: "Nagaland", type: "Central University", aisheCode: "U-14918" },
  { name: "Manipur University", city: "Imphal", state: "Manipur", type: "Central University", aisheCode: "U-14919" },
  { name: "Mizoram University", city: "Aizawl", state: "Mizoram", type: "Central University", aisheCode: "U-14920" },
  { name: "Sikkim University", city: "Gangtok", state: "Sikkim", type: "Central University", aisheCode: "U-14921" },
  { name: "Indira Gandhi National Open University", city: "New Delhi", state: "Delhi", type: "Central University", aisheCode: "U-14922" },
  { name: "Mahatma Gandhi Central University", city: "Motihari", state: "Bihar", type: "Central University", aisheCode: "U-55914" },
  { name: "Central Tribal University of Andhra Pradesh", city: "Vizianagaram", state: "Andhra Pradesh", type: "Central University", aisheCode: "U-55915" },
  { name: "Nalanda University", city: "Rajgir", state: "Bihar", type: "Central University", aisheCode: "U-55916" },
  { name: "South Asian University", city: "New Delhi", state: "Delhi", type: "Central University", aisheCode: "U-55917" },
  { name: "Dr Harisingh Gour Vishwavidyalaya", city: "Sagar", state: "Madhya Pradesh", type: "Central University", aisheCode: "U-14923" },
  // ===== Top State Universities (100) =====
  { name: "Anna University", city: "Chennai", state: "Tamil Nadu", type: "State University" },
  { name: "Savitribai Phule Pune University", city: "Pune", state: "Maharashtra", type: "State University" },
  { name: "University of Mumbai", city: "Mumbai", state: "Maharashtra", type: "State University" },
  { name: "University of Calcutta", city: "Kolkata", state: "West Bengal", type: "State University" },
  { name: "University of Madras", city: "Chennai", state: "Tamil Nadu", type: "State University" },
  { name: "Jadavpur University", city: "Kolkata", state: "West Bengal", type: "State University" },
  { name: "Osmania University", city: "Hyderabad", state: "Telangana", type: "State University" },
  { name: "Panjab University", city: "Chandigarh", state: "Chandigarh", type: "State University" },
  { name: "University of Rajasthan", city: "Jaipur", state: "Rajasthan", type: "State University" },
  { name: "Gujarat University", city: "Ahmedabad", state: "Gujarat", type: "State University" },
  { name: "Bangalore University", city: "Bangalore", state: "Karnataka", type: "State University" },
  { name: "University of Lucknow", city: "Lucknow", state: "Uttar Pradesh", type: "State University" },
  { name: "University of Allahabad", city: "Prayagraj", state: "Uttar Pradesh", type: "State University" },
  { name: "Patna University", city: "Patna", state: "Bihar", type: "State University" },
  { name: "Gauhati University", city: "Guwahati", state: "Assam", type: "State University" },
  { name: "Utkal University", city: "Bhubaneswar", state: "Odisha", type: "State University" },
  { name: "Andhra University", city: "Visakhapatnam", state: "Andhra Pradesh", type: "State University" },
  { name: "Mysore University", city: "Mysore", state: "Karnataka", type: "State University" },
  { name: "University of Kerala", city: "Thiruvananthapuram", state: "Kerala", type: "State University" },
  { name: "Cochin University of Science and Technology", city: "Kochi", state: "Kerala", type: "State University" },
  { name: "Mahatma Gandhi University", city: "Kottayam", state: "Kerala", type: "State University" },
  { name: "Calicut University", city: "Malappuram", state: "Kerala", type: "State University" },
  { name: "Kannur University", city: "Kannur", state: "Kerala", type: "State University" },
  { name: "Bharathiar University", city: "Coimbatore", state: "Tamil Nadu", type: "State University" },
  { name: "Bharathidasan University", city: "Tiruchirappalli", state: "Tamil Nadu", type: "State University" },
  { name: "Madurai Kamaraj University", city: "Madurai", state: "Tamil Nadu", type: "State University" },
  { name: "Alagappa University", city: "Karaikudi", state: "Tamil Nadu", type: "State University" },
  { name: "Sri Venkateswara University", city: "Tirupati", state: "Andhra Pradesh", type: "State University" },
  { name: "Acharya Nagarjuna University", city: "Guntur", state: "Andhra Pradesh", type: "State University" },
  { name: "Kakatiya University", city: "Warangal", state: "Telangana", type: "State University" },
  { name: "Telangana University", city: "Nizamabad", state: "Telangana", type: "State University" },
  { name: "Gulbarga University", city: "Kalaburagi", state: "Karnataka", type: "State University" },
  { name: "Karnatak University", city: "Dharwad", state: "Karnataka", type: "State University" },
  { name: "Mangalore University", city: "Mangalore", state: "Karnataka", type: "State University" },
  { name: "Visvesvaraya Technological University", city: "Belgaum", state: "Karnataka", type: "State University" },
  { name: "Shivaji University", city: "Kolhapur", state: "Maharashtra", type: "State University" },
  { name: "Dr Babasaheb Ambedkar Marathwada University", city: "Aurangabad", state: "Maharashtra", type: "State University" },
  { name: "Rashtrasant Tukadoji Maharaj Nagpur University", city: "Nagpur", state: "Maharashtra", type: "State University" },
  { name: "North Maharashtra University", city: "Jalgaon", state: "Maharashtra", type: "State University" },
  { name: "Sant Gadge Baba Amravati University", city: "Amravati", state: "Maharashtra", type: "State University" },
  { name: "Maharaja Sayajirao University of Baroda", city: "Vadodara", state: "Gujarat", type: "State University" },
  { name: "Saurashtra University", city: "Rajkot", state: "Gujarat", type: "State University" },
  { name: "Sardar Patel University", city: "Anand", state: "Gujarat", type: "State University" },
  { name: "Gujarat Technological University", city: "Ahmedabad", state: "Gujarat", type: "State University" },
  { name: "Mohanlal Sukhadia University", city: "Udaipur", state: "Rajasthan", type: "State University" },
  { name: "Jai Narain Vyas University", city: "Jodhpur", state: "Rajasthan", type: "State University" },
  { name: "Maharshi Dayanand University", city: "Rohtak", state: "Haryana", type: "State University" },
  { name: "Kurukshetra University", city: "Kurukshetra", state: "Haryana", type: "State University" },
  { name: "Guru Nanak Dev University", city: "Amritsar", state: "Punjab", type: "State University" },
  { name: "Punjabi University", city: "Patiala", state: "Punjab", type: "State University" },
  { name: "Himachal Pradesh University", city: "Shimla", state: "Himachal Pradesh", type: "State University" },
  { name: "University of Jammu", city: "Jammu", state: "Jammu and Kashmir", type: "State University" },
  { name: "University of Kashmir", city: "Srinagar", state: "Jammu and Kashmir", type: "State University" },
  { name: "Chaudhary Charan Singh University", city: "Meerut", state: "Uttar Pradesh", type: "State University" },
  { name: "Dr Ram Manohar Lohia Avadh University", city: "Ayodhya", state: "Uttar Pradesh", type: "State University" },
  { name: "Mahatma Jyotiba Phule Rohilkhand University", city: "Bareilly", state: "Uttar Pradesh", type: "State University" },
  { name: "Deen Dayal Upadhyaya Gorakhpur University", city: "Gorakhpur", state: "Uttar Pradesh", type: "State University" },
  { name: "Veer Bahadur Singh Purvanchal University", city: "Jaunpur", state: "Uttar Pradesh", type: "State University" },
  { name: "Bundelkhand University", city: "Jhansi", state: "Uttar Pradesh", type: "State University" },
  { name: "Magadh University", city: "Bodh Gaya", state: "Bihar", type: "State University" },
  { name: "Lalit Narayan Mithila University", city: "Darbhanga", state: "Bihar", type: "State University" },
  { name: "Tilka Manjhi Bhagalpur University", city: "Bhagalpur", state: "Bihar", type: "State University" },
  { name: "Ranchi University", city: "Ranchi", state: "Jharkhand", type: "State University" },
  { name: "Berhampur University", city: "Berhampur", state: "Odisha", type: "State University" },
  { name: "Sambalpur University", city: "Sambalpur", state: "Odisha", type: "State University" },
  { name: "Ravenshaw University", city: "Cuttack", state: "Odisha", type: "State University" },
  { name: "Vidyasagar University", city: "Medinipur", state: "West Bengal", type: "State University" },
  { name: "North Bengal University", city: "Siliguri", state: "West Bengal", type: "State University" },
  { name: "Burdwan University", city: "Bardhaman", state: "West Bengal", type: "State University" },
  { name: "Kalyani University", city: "Kalyani", state: "West Bengal", type: "State University" },
  { name: "Dibrugarh University", city: "Dibrugarh", state: "Assam", type: "State University" },
  { name: "Cotton University", city: "Guwahati", state: "Assam", type: "State University" },
  { name: "Pt Ravishankar Shukla University", city: "Raipur", state: "Chhattisgarh", type: "State University" },
  { name: "Guru Ghasidas Vishwavidyalaya", city: "Bilaspur", state: "Chhattisgarh", type: "State University" },
  { name: "Barkatullah University", city: "Bhopal", state: "Madhya Pradesh", type: "State University" },
  { name: "Rani Durgavati Vishwavidyalaya", city: "Jabalpur", state: "Madhya Pradesh", type: "State University" },
  { name: "Devi Ahilya Vishwavidyalaya", city: "Indore", state: "Madhya Pradesh", type: "State University" },
  { name: "Jiwaji University", city: "Gwalior", state: "Madhya Pradesh", type: "State University" },
  { name: "Awadhesh Pratap Singh University", city: "Rewa", state: "Madhya Pradesh", type: "State University" },
  { name: "Vikram University", city: "Ujjain", state: "Madhya Pradesh", type: "State University" },
  { name: "Kumaun University", city: "Nainital", state: "Uttarakhand", type: "State University" },
  { name: "Goa University", city: "Taleigao", state: "Goa", type: "State University" },
  // ===== Top Private Universities (80) =====
  { name: "Manipal Academy of Higher Education", city: "Manipal", state: "Karnataka", type: "Private University" },
  { name: "Birla Institute of Technology and Science Pilani", city: "Pilani", state: "Rajasthan", type: "Private University" },
  { name: "Amrita Vishwa Vidyapeetham", city: "Coimbatore", state: "Tamil Nadu", type: "Private University" },
  { name: "Vellore Institute of Technology", city: "Vellore", state: "Tamil Nadu", type: "Private University" },
  { name: "SRM Institute of Science and Technology", city: "Chennai", state: "Tamil Nadu", type: "Private University" },
  { name: "KIIT University", city: "Bhubaneswar", state: "Odisha", type: "Private University" },
  { name: "Lovely Professional University", city: "Phagwara", state: "Punjab", type: "Private University" },
  { name: "Amity University", city: "Noida", state: "Uttar Pradesh", type: "Private University" },
  { name: "Thapar Institute of Engineering and Technology", city: "Patiala", state: "Punjab", type: "Private University" },
  { name: "Shiv Nadar University", city: "Greater Noida", state: "Uttar Pradesh", type: "Private University" },
  { name: "Ashoka University", city: "Sonipat", state: "Haryana", type: "Private University" },
  { name: "FLAME University", city: "Pune", state: "Maharashtra", type: "Private University" },
  { name: "O P Jindal Global University", city: "Sonipat", state: "Haryana", type: "Private University" },
  { name: "Symbiosis International University", city: "Pune", state: "Maharashtra", type: "Private University" },
  { name: "Christ University", city: "Bangalore", state: "Karnataka", type: "Private University" },
  { name: "NMIMS University", city: "Mumbai", state: "Maharashtra", type: "Private University" },
  { name: "Chandigarh University", city: "Mohali", state: "Punjab", type: "Private University" },
  { name: "Bennett University", city: "Greater Noida", state: "Uttar Pradesh", type: "Private University" },
  { name: "Jain University", city: "Bangalore", state: "Karnataka", type: "Private University" },
  { name: "UPES Dehradun", city: "Dehradun", state: "Uttarakhand", type: "Private University" },
  { name: "SRM University Andhra Pradesh", city: "Amaravati", state: "Andhra Pradesh", type: "Private University" },
  { name: "VIT AP University", city: "Amaravati", state: "Andhra Pradesh", type: "Private University" },
  { name: "VIT Bhopal University", city: "Bhopal", state: "Madhya Pradesh", type: "Private University" },
  { name: "BITS Pilani Goa Campus", city: "Zuarinagar", state: "Goa", type: "Private University" },
  { name: "BITS Pilani Hyderabad Campus", city: "Hyderabad", state: "Telangana", type: "Private University" },
  { name: "Nirma University", city: "Ahmedabad", state: "Gujarat", type: "Private University" },
  { name: "Chitkara University", city: "Rajpura", state: "Punjab", type: "Private University" },
  { name: "Dhirubhai Ambani Institute of Information and Communication Technology", city: "Gandhinagar", state: "Gujarat", type: "Private University" },
  { name: "Kalinga Institute of Industrial Technology", city: "Bhubaneswar", state: "Odisha", type: "Private University" },
  { name: "Woxsen University", city: "Hyderabad", state: "Telangana", type: "Private University" },
  { name: "Shoolini University", city: "Solan", state: "Himachal Pradesh", type: "Private University" },
  { name: "Jaypee Institute of Information Technology", city: "Noida", state: "Uttar Pradesh", type: "Private University" },
  { name: "PES University", city: "Bangalore", state: "Karnataka", type: "Private University" },
  { name: "MIT World Peace University", city: "Pune", state: "Maharashtra", type: "Private University" },
  { name: "KL University", city: "Guntur", state: "Andhra Pradesh", type: "Private University" },
  { name: "Presidency University", city: "Bangalore", state: "Karnataka", type: "Private University" },
  { name: "Graphic Era University", city: "Dehradun", state: "Uttarakhand", type: "Private University" },
  { name: "Hindustan Institute of Technology and Science", city: "Chennai", state: "Tamil Nadu", type: "Private University" },
  { name: "Vel Tech Rangarajan Dr Sagunthala R and D Institute", city: "Chennai", state: "Tamil Nadu", type: "Private University" },
  { name: "Sathyabama Institute of Science and Technology", city: "Chennai", state: "Tamil Nadu", type: "Private University" },
  { name: "Shanmugha Arts Science Technology and Research Academy", city: "Thanjavur", state: "Tamil Nadu", type: "Private University" },
  { name: "Sri Ramachandra Institute of Higher Education", city: "Chennai", state: "Tamil Nadu", type: "Private University" },
  { name: "Saveetha Institute of Medical and Technical Sciences", city: "Chennai", state: "Tamil Nadu", type: "Private University" },
  { name: "Bharath Institute of Higher Education and Research", city: "Chennai", state: "Tamil Nadu", type: "Private University" },
  { name: "DIT University", city: "Dehradun", state: "Uttarakhand", type: "Private University" },
  { name: "GD Goenka University", city: "Gurugram", state: "Haryana", type: "Private University" },
  { name: "Manav Rachna International Institute of Research and Studies", city: "Faridabad", state: "Haryana", type: "Private University" },
  { name: "ITM University Gwalior", city: "Gwalior", state: "Madhya Pradesh", type: "Private University" },
  { name: "REVA University", city: "Bangalore", state: "Karnataka", type: "Private University" },
  { name: "JSS Academy of Higher Education and Research", city: "Mysore", state: "Karnataka", type: "Private University" },
  { name: "KLE Technological University", city: "Hubli", state: "Karnataka", type: "Private University" },
  { name: "Alliance University", city: "Bangalore", state: "Karnataka", type: "Private University" },
  { name: "MS Ramaiah University of Applied Sciences", city: "Bangalore", state: "Karnataka", type: "Private University" },
  { name: "CMR University", city: "Bangalore", state: "Karnataka", type: "Private University" },
  { name: "GITAM University", city: "Visakhapatnam", state: "Andhra Pradesh", type: "Private University" },
  { name: "Vignan University", city: "Guntur", state: "Andhra Pradesh", type: "Private University" },
  { name: "Koneru Lakshmaiah Education Foundation", city: "Vaddeswaram", state: "Andhra Pradesh", type: "Private University" },
  { name: "Centurion University of Technology and Management", city: "Bhubaneswar", state: "Odisha", type: "Private University" },
  { name: "SOA University", city: "Bhubaneswar", state: "Odisha", type: "Private University" },
  { name: "Xavier University", city: "Bhubaneswar", state: "Odisha", type: "Private University" },
  { name: "ICFAI Foundation for Higher Education", city: "Hyderabad", state: "Telangana", type: "Private University" },
  { name: "Mahindra University", city: "Hyderabad", state: "Telangana", type: "Private University" },
  { name: "Krea University", city: "Sri City", state: "Andhra Pradesh", type: "Private University" },
  { name: "Plaksha University", city: "Mohali", state: "Punjab", type: "Private University" },
  { name: "Azim Premji University", city: "Bangalore", state: "Karnataka", type: "Private University" },
  { name: "Indian School of Business", city: "Hyderabad", state: "Telangana", type: "Private University" },
  { name: "XLRI Xavier School of Management", city: "Jamshedpur", state: "Jharkhand", type: "Private University" },
  { name: "SP Jain Institute of Management and Research", city: "Mumbai", state: "Maharashtra", type: "Private University" },
  { name: "Great Lakes Institute of Management", city: "Chennai", state: "Tamil Nadu", type: "Private University" },
  { name: "MICA Ahmedabad", city: "Ahmedabad", state: "Gujarat", type: "Private University" },
  { name: "Narsee Monjee Institute of Management Studies", city: "Mumbai", state: "Maharashtra", type: "Private University" },
  { name: "Birla Institute of Management Technology", city: "Greater Noida", state: "Uttar Pradesh", type: "Private University" },
  { name: "International Management Institute", city: "New Delhi", state: "Delhi", type: "Private University" },
  { name: "T A Pai Management Institute", city: "Manipal", state: "Karnataka", type: "Private University" },
  { name: "FORE School of Management", city: "New Delhi", state: "Delhi", type: "Private University" },
  { name: "Galgotias University", city: "Greater Noida", state: "Uttar Pradesh", type: "Private University" },
  { name: "SRM University Sikkim", city: "Gangtok", state: "Sikkim", type: "Private University" },
  { name: "Adamas University", city: "Kolkata", state: "West Bengal", type: "Private University" },
  { name: "Sister Nivedita University", city: "Kolkata", state: "West Bengal", type: "Private University" },
  // ===== Top Deemed Universities (50) =====
  { name: "Indian Statistical Institute", city: "Kolkata", state: "West Bengal", type: "Deemed University" },
  { name: "PGIMER Chandigarh", city: "Chandigarh", state: "Chandigarh", type: "Deemed University" },
  { name: "NIMHANS Bangalore", city: "Bangalore", state: "Karnataka", type: "Deemed University" },
  { name: "SGPGI Lucknow", city: "Lucknow", state: "Uttar Pradesh", type: "Deemed University" },
  { name: "Indian Agricultural Research Institute", city: "New Delhi", state: "Delhi", type: "Deemed University" },
  { name: "Indian Veterinary Research Institute", city: "Bareilly", state: "Uttar Pradesh", type: "Deemed University" },
  { name: "Tata Institute of Social Sciences", city: "Mumbai", state: "Maharashtra", type: "Deemed University" },
  { name: "Tata Institute of Fundamental Research", city: "Mumbai", state: "Maharashtra", type: "Deemed University" },
  { name: "Institute of Chemical Technology", city: "Mumbai", state: "Maharashtra", type: "Deemed University" },
  { name: "Homi Bhabha National Institute", city: "Mumbai", state: "Maharashtra", type: "Deemed University" },
  { name: "Birla Institute of Technology Mesra", city: "Ranchi", state: "Jharkhand", type: "Deemed University" },
  { name: "IISER Pune", city: "Pune", state: "Maharashtra", type: "Deemed University" },
  { name: "IISER Kolkata", city: "Mohanpur", state: "West Bengal", type: "Deemed University" },
  { name: "IISER Mohali", city: "Mohali", state: "Punjab", type: "Deemed University" },
  { name: "IISER Bhopal", city: "Bhopal", state: "Madhya Pradesh", type: "Deemed University" },
  { name: "IISER Thiruvananthapuram", city: "Thiruvananthapuram", state: "Kerala", type: "Deemed University" },
  { name: "IISER Tirupati", city: "Tirupati", state: "Andhra Pradesh", type: "Deemed University" },
  { name: "IISER Berhampur", city: "Berhampur", state: "Odisha", type: "Deemed University" },
  { name: "National Institute of Design Ahmedabad", city: "Ahmedabad", state: "Gujarat", type: "Deemed University" },
  { name: "National Institute of Fashion Technology Delhi", city: "New Delhi", state: "Delhi", type: "Deemed University" },
  { name: "School of Planning and Architecture Delhi", city: "New Delhi", state: "Delhi", type: "Deemed University" },
  { name: "Indian Institute of Space Science and Technology", city: "Thiruvananthapuram", state: "Kerala", type: "Deemed University" },
  { name: "National Institute of Mental Health and Neurosciences", city: "Bangalore", state: "Karnataka", type: "Deemed University" },
  { name: "Lakshmibai National Institute of Physical Education", city: "Gwalior", state: "Madhya Pradesh", type: "Deemed University" },
  { name: "National Museum Institute", city: "New Delhi", state: "Delhi", type: "Deemed University" },
  { name: "Dayalbagh Educational Institute", city: "Agra", state: "Uttar Pradesh", type: "Deemed University" },
  { name: "Deccan College Postgraduate and Research Institute", city: "Pune", state: "Maharashtra", type: "Deemed University" },
  { name: "Gokhale Institute of Politics and Economics", city: "Pune", state: "Maharashtra", type: "Deemed University" },
  { name: "IIT Institute of Design", city: "Ahmedabad", state: "Gujarat", type: "Deemed University" },
  { name: "Indian Institute of Packaging", city: "Mumbai", state: "Maharashtra", type: "Deemed University" },
  { name: "Nitte University", city: "Mangalore", state: "Karnataka", type: "Deemed University" },
  { name: "Yenepoya University", city: "Mangalore", state: "Karnataka", type: "Deemed University" },
  { name: "Dr DY Patil Vidyapeeth Pune", city: "Pune", state: "Maharashtra", type: "Deemed University" },
  { name: "Koneru Lakshmaiah Education Foundation Hyderabad", city: "Hyderabad", state: "Telangana", type: "Deemed University" },
  { name: "Sri Balaji Vidyapeeth", city: "Puducherry", state: "Puducherry", type: "Deemed University" },
  { name: "Jamia Hamdard", city: "New Delhi", state: "Delhi", type: "Deemed University" },
  { name: "TERI School of Advanced Studies", city: "New Delhi", state: "Delhi", type: "Deemed University" },
  { name: "Indian Law Institute", city: "New Delhi", state: "Delhi", type: "Deemed University" },
  // ===== Top Engineering Colleges (non-IIT/NIT/IIIT) (100) =====
  { name: "Delhi Technological University", city: "New Delhi", state: "Delhi", type: "Engineering College" },
  { name: "Netaji Subhas University of Technology", city: "New Delhi", state: "Delhi", type: "Engineering College" },
  { name: "PEC University of Technology", city: "Chandigarh", state: "Chandigarh", type: "Engineering College" },
  { name: "College of Engineering Pune", city: "Pune", state: "Maharashtra", type: "Engineering College" },
  { name: "College of Engineering Trivandrum", city: "Thiruvananthapuram", state: "Kerala", type: "Engineering College" },
  { name: "PSG College of Technology", city: "Coimbatore", state: "Tamil Nadu", type: "Engineering College" },
  { name: "RV College of Engineering", city: "Bangalore", state: "Karnataka", type: "Engineering College" },
  { name: "BMS College of Engineering", city: "Bangalore", state: "Karnataka", type: "Engineering College" },
  { name: "MS Ramaiah Institute of Technology", city: "Bangalore", state: "Karnataka", type: "Engineering College" },
  { name: "Sri Sivasubramaniya Nadar College of Engineering", city: "Kalavakkam", state: "Tamil Nadu", type: "Engineering College" },
  { name: "Thiagarajar College of Engineering", city: "Madurai", state: "Tamil Nadu", type: "Engineering College" },
  { name: "Government College of Technology Coimbatore", city: "Coimbatore", state: "Tamil Nadu", type: "Engineering College" },
  { name: "Coimbatore Institute of Technology", city: "Coimbatore", state: "Tamil Nadu", type: "Engineering College" },
  { name: "Kongu Engineering College", city: "Erode", state: "Tamil Nadu", type: "Engineering College" },
  { name: "Mepco Schlenk Engineering College", city: "Sivakasi", state: "Tamil Nadu", type: "Engineering College" },
  { name: "Kumaraguru College of Technology", city: "Coimbatore", state: "Tamil Nadu", type: "Engineering College" },
  { name: "Sona College of Technology", city: "Salem", state: "Tamil Nadu", type: "Engineering College" },
  { name: "Government Engineering College Thrissur", city: "Thrissur", state: "Kerala", type: "Engineering College" },
  { name: "Model Engineering College Kochi", city: "Kochi", state: "Kerala", type: "Engineering College" },
  { name: "TKM College of Engineering", city: "Kollam", state: "Kerala", type: "Engineering College" },
  { name: "National Institute of Engineering Mysore", city: "Mysore", state: "Karnataka", type: "Engineering College" },
  { name: "BV Bhoomaraddi College of Engineering and Technology", city: "Hubli", state: "Karnataka", type: "Engineering College" },
  { name: "SDM College of Engineering and Technology", city: "Dharwad", state: "Karnataka", type: "Engineering College" },
  { name: "Siddaganga Institute of Technology", city: "Tumkur", state: "Karnataka", type: "Engineering College" },
  { name: "Dayananda Sagar College of Engineering", city: "Bangalore", state: "Karnataka", type: "Engineering College" },
  { name: "New Horizon College of Engineering", city: "Bangalore", state: "Karnataka", type: "Engineering College" },
  { name: "Walchand College of Engineering", city: "Sangli", state: "Maharashtra", type: "Engineering College" },
  { name: "Veermata Jijabai Technological Institute", city: "Mumbai", state: "Maharashtra", type: "Engineering College" },
  { name: "Sardar Patel College of Engineering", city: "Mumbai", state: "Maharashtra", type: "Engineering College" },
  { name: "Fr Conceicao Rodrigues College of Engineering", city: "Mumbai", state: "Maharashtra", type: "Engineering College" },
  { name: "DJ Sanghvi College of Engineering", city: "Mumbai", state: "Maharashtra", type: "Engineering College" },
  { name: "KJ Somaiya College of Engineering", city: "Mumbai", state: "Maharashtra", type: "Engineering College" },
  { name: "Thadomal Shahani Engineering College", city: "Mumbai", state: "Maharashtra", type: "Engineering College" },
  { name: "Vishwakarma Institute of Technology", city: "Pune", state: "Maharashtra", type: "Engineering College" },
  { name: "Pune Institute of Computer Technology", city: "Pune", state: "Maharashtra", type: "Engineering College" },
  { name: "Army Institute of Technology", city: "Pune", state: "Maharashtra", type: "Engineering College" },
  { name: "Cummins College of Engineering for Women", city: "Pune", state: "Maharashtra", type: "Engineering College" },
  { name: "Government College of Engineering Aurangabad", city: "Aurangabad", state: "Maharashtra", type: "Engineering College" },
  { name: "LD College of Engineering", city: "Ahmedabad", state: "Gujarat", type: "Engineering College" },
  { name: "BVM Engineering College", city: "Anand", state: "Gujarat", type: "Engineering College" },
  { name: "Birla Vishvakarma Mahavidyalaya", city: "Anand", state: "Gujarat", type: "Engineering College" },
  { name: "Harcourt Butler Technical University", city: "Kanpur", state: "Uttar Pradesh", type: "Engineering College" },
  { name: "Institute of Engineering and Technology Lucknow", city: "Lucknow", state: "Uttar Pradesh", type: "Engineering College" },
  { name: "Jabalpur Engineering College", city: "Jabalpur", state: "Madhya Pradesh", type: "Engineering College" },
  { name: "Maulana Azad National Institute of Technology", city: "Bhopal", state: "Madhya Pradesh", type: "Engineering College" },
  { name: "University Institute of Engineering and Technology Chandigarh", city: "Chandigarh", state: "Chandigarh", type: "Engineering College" },
  { name: "Heritage Institute of Technology", city: "Kolkata", state: "West Bengal", type: "Engineering College" },
  { name: "Institute of Engineering and Management", city: "Kolkata", state: "West Bengal", type: "Engineering College" },
  { name: "Techno India University", city: "Kolkata", state: "West Bengal", type: "Engineering College" },
  { name: "Bengal Engineering and Science University", city: "Howrah", state: "West Bengal", type: "Engineering College" },
  { name: "Jorhat Engineering College", city: "Jorhat", state: "Assam", type: "Engineering College" },
  { name: "Assam Engineering College", city: "Guwahati", state: "Assam", type: "Engineering College" },
  { name: "IIMT College of Engineering", city: "Greater Noida", state: "Uttar Pradesh", type: "Engineering College" },
  { name: "JSS Science and Technology University", city: "Mysore", state: "Karnataka", type: "Engineering College" },
  { name: "Rajalakshmi Engineering College", city: "Chennai", state: "Tamil Nadu", type: "Engineering College" },
  { name: "St Josephs College of Engineering", city: "Chennai", state: "Tamil Nadu", type: "Engineering College" },
  { name: "Easwari Engineering College", city: "Chennai", state: "Tamil Nadu", type: "Engineering College" },
  { name: "SRM Valliammai Engineering College", city: "Chennai", state: "Tamil Nadu", type: "Engineering College" },
  { name: "Velammal Engineering College", city: "Chennai", state: "Tamil Nadu", type: "Engineering College" },
  { name: "R M K Engineering College", city: "Chennai", state: "Tamil Nadu", type: "Engineering College" },
  // ===== Top Medical Colleges (non-AIIMS) (60) =====
  { name: "Christian Medical College Vellore", city: "Vellore", state: "Tamil Nadu", type: "Medical College" },
  { name: "JIPMER Puducherry", city: "Puducherry", state: "Puducherry", type: "Medical College" },
  { name: "Armed Forces Medical College", city: "Pune", state: "Maharashtra", type: "Medical College" },
  { name: "Maulana Azad Medical College", city: "New Delhi", state: "Delhi", type: "Medical College" },
  { name: "King George Medical University", city: "Lucknow", state: "Uttar Pradesh", type: "Medical College" },
  { name: "Grant Medical College", city: "Mumbai", state: "Maharashtra", type: "Medical College" },
  { name: "Madras Medical College", city: "Chennai", state: "Tamil Nadu", type: "Medical College" },
  { name: "Seth GS Medical College", city: "Mumbai", state: "Maharashtra", type: "Medical College" },
  { name: "Lady Hardinge Medical College", city: "New Delhi", state: "Delhi", type: "Medical College" },
  { name: "Stanley Medical College", city: "Chennai", state: "Tamil Nadu", type: "Medical College" },
  { name: "BJ Medical College", city: "Ahmedabad", state: "Gujarat", type: "Medical College" },
  { name: "Government Medical College Chandigarh", city: "Chandigarh", state: "Chandigarh", type: "Medical College" },
  { name: "Kasturba Medical College Manipal", city: "Manipal", state: "Karnataka", type: "Medical College" },
  { name: "Kasturba Medical College Mangalore", city: "Mangalore", state: "Karnataka", type: "Medical College" },
  { name: "St Johns Medical College", city: "Bangalore", state: "Karnataka", type: "Medical College" },
  { name: "Government Medical College Thiruvananthapuram", city: "Thiruvananthapuram", state: "Kerala", type: "Medical College" },
  { name: "Government Medical College Kozhikode", city: "Kozhikode", state: "Kerala", type: "Medical College" },
  { name: "Amrita School of Medicine", city: "Kochi", state: "Kerala", type: "Medical College" },
  { name: "Bangalore Medical College and Research Institute", city: "Bangalore", state: "Karnataka", type: "Medical College" },
  { name: "Topiwala National Medical College", city: "Mumbai", state: "Maharashtra", type: "Medical College" },
  { name: "LTMMC and LTMGH Sion", city: "Mumbai", state: "Maharashtra", type: "Medical College" },
  { name: "Government Medical College Nagpur", city: "Nagpur", state: "Maharashtra", type: "Medical College" },
  { name: "Government Medical College Aurangabad", city: "Aurangabad", state: "Maharashtra", type: "Medical College" },
  { name: "BJ Government Medical College Pune", city: "Pune", state: "Maharashtra", type: "Medical College" },
  { name: "Institute of Medical Sciences BHU", city: "Varanasi", state: "Uttar Pradesh", type: "Medical College" },
  { name: "Calcutta National Medical College", city: "Kolkata", state: "West Bengal", type: "Medical College" },
  { name: "RG Kar Medical College", city: "Kolkata", state: "West Bengal", type: "Medical College" },
  { name: "Medical College Kolkata", city: "Kolkata", state: "West Bengal", type: "Medical College" },
  { name: "NRS Medical College", city: "Kolkata", state: "West Bengal", type: "Medical College" },
  { name: "Patna Medical College", city: "Patna", state: "Bihar", type: "Medical College" },
  { name: "Government Medical College Patiala", city: "Patiala", state: "Punjab", type: "Medical College" },
  { name: "Government Medical College Amritsar", city: "Amritsar", state: "Punjab", type: "Medical College" },
  { name: "SMS Medical College", city: "Jaipur", state: "Rajasthan", type: "Medical College" },
  { name: "SN Medical College Jodhpur", city: "Jodhpur", state: "Rajasthan", type: "Medical College" },
  { name: "Indira Gandhi Medical College Shimla", city: "Shimla", state: "Himachal Pradesh", type: "Medical College" },
  { name: "Dayanand Medical College", city: "Ludhiana", state: "Punjab", type: "Medical College" },
  { name: "SCB Medical College", city: "Cuttack", state: "Odisha", type: "Medical College" },
  { name: "VIMSAR Burla", city: "Sambalpur", state: "Odisha", type: "Medical College" },
  { name: "Gandhi Medical College", city: "Hyderabad", state: "Telangana", type: "Medical College" },
  { name: "Osmania Medical College", city: "Hyderabad", state: "Telangana", type: "Medical College" },
  // ===== Top Arts, Commerce and Science Colleges (100) =====
  { name: "Hindu College", city: "New Delhi", state: "Delhi", type: "Arts and Science College" },
  { name: "Miranda House", city: "New Delhi", state: "Delhi", type: "Arts and Science College" },
  { name: "Hans Raj College", city: "New Delhi", state: "Delhi", type: "Arts and Science College" },
  { name: "Kirori Mal College", city: "New Delhi", state: "Delhi", type: "Arts and Science College" },
  { name: "St Stephens College", city: "New Delhi", state: "Delhi", type: "Arts and Science College" },
  { name: "Shri Ram College of Commerce", city: "New Delhi", state: "Delhi", type: "Arts and Science College" },
  { name: "Lady Shri Ram College for Women", city: "New Delhi", state: "Delhi", type: "Arts and Science College" },
  { name: "Ramjas College", city: "New Delhi", state: "Delhi", type: "Arts and Science College" },
  { name: "Daulat Ram College", city: "New Delhi", state: "Delhi", type: "Arts and Science College" },
  { name: "Gargi College", city: "New Delhi", state: "Delhi", type: "Arts and Science College" },
  { name: "Indraprastha College for Women", city: "New Delhi", state: "Delhi", type: "Arts and Science College" },
  { name: "Kamala Nehru College", city: "New Delhi", state: "Delhi", type: "Arts and Science College" },
  { name: "Jesus and Mary College", city: "New Delhi", state: "Delhi", type: "Arts and Science College" },
  { name: "Deshbandhu College", city: "New Delhi", state: "Delhi", type: "Arts and Science College" },
  { name: "Atma Ram Sanatan Dharma College", city: "New Delhi", state: "Delhi", type: "Arts and Science College" },
  { name: "Sri Venkateswara College", city: "New Delhi", state: "Delhi", type: "Arts and Science College" },
  { name: "Dyal Singh College", city: "New Delhi", state: "Delhi", type: "Arts and Science College" },
  { name: "Shaheed Bhagat Singh College", city: "New Delhi", state: "Delhi", type: "Arts and Science College" },
  { name: "Maitreyi College", city: "New Delhi", state: "Delhi", type: "Arts and Science College" },
  { name: "Acharya Narendra Dev College", city: "New Delhi", state: "Delhi", type: "Arts and Science College" },
  { name: "Sri Guru Gobind Singh College of Commerce", city: "New Delhi", state: "Delhi", type: "Arts and Science College" },
  { name: "Loyola College", city: "Chennai", state: "Tamil Nadu", type: "Arts and Science College" },
  { name: "Madras Christian College", city: "Chennai", state: "Tamil Nadu", type: "Arts and Science College" },
  { name: "Presidency College Chennai", city: "Chennai", state: "Tamil Nadu", type: "Arts and Science College" },
  { name: "Ethiraj College for Women", city: "Chennai", state: "Tamil Nadu", type: "Arts and Science College" },
  { name: "Stella Maris College", city: "Chennai", state: "Tamil Nadu", type: "Arts and Science College" },
  { name: "Womens Christian College", city: "Chennai", state: "Tamil Nadu", type: "Arts and Science College" },
  { name: "St Xaviers College Mumbai", city: "Mumbai", state: "Maharashtra", type: "Arts and Science College" },
  { name: "Elphinstone College", city: "Mumbai", state: "Maharashtra", type: "Arts and Science College" },
  { name: "St Xaviers College Kolkata", city: "Kolkata", state: "West Bengal", type: "Arts and Science College" },
  { name: "Presidency University Kolkata", city: "Kolkata", state: "West Bengal", type: "Arts and Science College" },
  { name: "Scottish Church College", city: "Kolkata", state: "West Bengal", type: "Arts and Science College" },
  { name: "Bethune College", city: "Kolkata", state: "West Bengal", type: "Arts and Science College" },
  { name: "Loreto College", city: "Kolkata", state: "West Bengal", type: "Arts and Science College" },
  { name: "Fergusson College", city: "Pune", state: "Maharashtra", type: "Arts and Science College" },
  { name: "SP College Pune", city: "Pune", state: "Maharashtra", type: "Arts and Science College" },
  { name: "Symbiosis College of Arts and Commerce", city: "Pune", state: "Maharashtra", type: "Arts and Science College" },
  { name: "Mount Carmel College", city: "Bangalore", state: "Karnataka", type: "Arts and Science College" },
  { name: "St Josephs College Bangalore", city: "Bangalore", state: "Karnataka", type: "Arts and Science College" },
  { name: "Maharajas College Mysore", city: "Mysore", state: "Karnataka", type: "Arts and Science College" },
  { name: "St Aloysius College Mangalore", city: "Mangalore", state: "Karnataka", type: "Arts and Science College" },
  { name: "Government Arts College Coimbatore", city: "Coimbatore", state: "Tamil Nadu", type: "Arts and Science College" },
  { name: "Maharajas College Ernakulam", city: "Kochi", state: "Kerala", type: "Arts and Science College" },
  { name: "CMS College Kottayam", city: "Kottayam", state: "Kerala", type: "Arts and Science College" },
  { name: "Nirmala College Muvattupuzha", city: "Muvattupuzha", state: "Kerala", type: "Arts and Science College" },
  { name: "MA College Kothamangalam", city: "Kothamangalam", state: "Kerala", type: "Arts and Science College" },
  { name: "St Xaviers College Ahmedabad", city: "Ahmedabad", state: "Gujarat", type: "Arts and Science College" },
  { name: "HL College of Commerce", city: "Ahmedabad", state: "Gujarat", type: "Arts and Science College" },
  { name: "Narsee Monjee College of Commerce and Economics", city: "Mumbai", state: "Maharashtra", type: "Arts and Science College" },
  { name: "HR College of Commerce and Economics", city: "Mumbai", state: "Maharashtra", type: "Arts and Science College" },
  { name: "Jai Hind College", city: "Mumbai", state: "Maharashtra", type: "Arts and Science College" },
  { name: "KC College", city: "Mumbai", state: "Maharashtra", type: "Arts and Science College" },
  { name: "Ruia College", city: "Mumbai", state: "Maharashtra", type: "Arts and Science College" },
  { name: "Mithibai College", city: "Mumbai", state: "Maharashtra", type: "Arts and Science College" },
  { name: "Wilson College", city: "Mumbai", state: "Maharashtra", type: "Arts and Science College" },
  { name: "Sophia College for Women", city: "Mumbai", state: "Maharashtra", type: "Arts and Science College" },
  { name: "DAV College Chandigarh", city: "Chandigarh", state: "Chandigarh", type: "Arts and Science College" },
  { name: "Government College for Girls Chandigarh", city: "Chandigarh", state: "Chandigarh", type: "Arts and Science College" },
  { name: "SD College Chandigarh", city: "Chandigarh", state: "Chandigarh", type: "Arts and Science College" },
  { name: "MCM DAV College for Women", city: "Chandigarh", state: "Chandigarh", type: "Arts and Science College" },
  { name: "Khalsa College Amritsar", city: "Amritsar", state: "Punjab", type: "Arts and Science College" },
  { name: "Government College for Women Thiruvananthapuram", city: "Thiruvananthapuram", state: "Kerala", type: "Arts and Science College" },
  { name: "Sri Guru Tegh Bahadur Khalsa College", city: "New Delhi", state: "Delhi", type: "Arts and Science College" },
  { name: "Janki Devi Memorial College", city: "New Delhi", state: "Delhi", type: "Arts and Science College" },
  { name: "Sri Aurobindo College", city: "New Delhi", state: "Delhi", type: "Arts and Science College" },
  { name: "Hansraj College", city: "New Delhi", state: "Delhi", type: "Arts and Science College" },
  { name: "BN College Patna", city: "Patna", state: "Bihar", type: "Arts and Science College" },
  { name: "Patna Science College", city: "Patna", state: "Bihar", type: "Arts and Science College" },
  { name: "Patna Womens College", city: "Patna", state: "Bihar", type: "Arts and Science College" },
  { name: "AN College Patna", city: "Patna", state: "Bihar", type: "Arts and Science College" },
  { name: "Ravenshaw University College", city: "Cuttack", state: "Odisha", type: "Arts and Science College" },
  { name: "BJB Autonomous College", city: "Bhubaneswar", state: "Odisha", type: "Arts and Science College" },
  { name: "Nizam College", city: "Hyderabad", state: "Telangana", type: "Arts and Science College" },
  { name: "Government City College", city: "Hyderabad", state: "Telangana", type: "Arts and Science College" },
  { name: "St Francis College for Women", city: "Hyderabad", state: "Telangana", type: "Arts and Science College" },
  { name: "Andhra Loyola College", city: "Vijayawada", state: "Andhra Pradesh", type: "Arts and Science College" },
  { name: "Maharanis Science College for Women", city: "Bangalore", state: "Karnataka", type: "Arts and Science College" },
  // ===== Other Notable Institutions (100+) =====
  { name: "National Institute of Pharmaceutical Education and Research Mohali", city: "Mohali", state: "Punjab", type: "Research Institute" },
  { name: "National Institute of Pharmaceutical Education and Research Hyderabad", city: "Hyderabad", state: "Telangana", type: "Research Institute" },
  { name: "Central Drug Research Institute", city: "Lucknow", state: "Uttar Pradesh", type: "Research Institute" },
  { name: "Indian Institute of Petroleum and Energy", city: "Visakhapatnam", state: "Andhra Pradesh", type: "Research Institute" },
  { name: "Indian Institute of Engineering Science and Technology Shibpur", city: "Howrah", state: "West Bengal", type: "Engineering College" },
  { name: "National Forensic Sciences University", city: "Gandhinagar", state: "Gujarat", type: "Central University" },
  { name: "Indian Maritime University", city: "Chennai", state: "Tamil Nadu", type: "Central University" },
  { name: "Atal Bihari Vajpayee Indian Institute of Information Technology and Management Gwalior", city: "Gwalior", state: "Madhya Pradesh", type: "IIIT" },
  { name: "National Institute of Food Technology Entrepreneurship and Management", city: "Sonipat", state: "Haryana", type: "Research Institute" },
  { name: "Central Institute of Fisheries Education", city: "Mumbai", state: "Maharashtra", type: "Research Institute" },
  { name: "Film and Television Institute of India", city: "Pune", state: "Maharashtra", type: "Arts Institute" },
  { name: "National School of Drama", city: "New Delhi", state: "Delhi", type: "Arts Institute" },
  { name: "Satyajit Ray Film and Television Institute", city: "Kolkata", state: "West Bengal", type: "Arts Institute" },
  { name: "National Institute of Design Ahmedabad", city: "Ahmedabad", state: "Gujarat", type: "Design Institute" },
  { name: "National Institute of Design Gandhinagar", city: "Gandhinagar", state: "Gujarat", type: "Design Institute" },
  { name: "National Institute of Design Bangalore", city: "Bangalore", state: "Karnataka", type: "Design Institute" },
  { name: "Indian Institute of Handloom Technology", city: "Salem", state: "Tamil Nadu", type: "Technical Institute" },
  { name: "Central Institute of Plastics Engineering and Technology", city: "Chennai", state: "Tamil Nadu", type: "Technical Institute" },
  { name: "School of Planning and Architecture Bhopal", city: "Bhopal", state: "Madhya Pradesh", type: "Architecture Institute" },
  { name: "School of Planning and Architecture Vijayawada", city: "Vijayawada", state: "Andhra Pradesh", type: "Architecture Institute" },
  { name: "Indian Institute of Management Bangalore", city: "Bangalore", state: "Karnataka", type: "Management Institute" },
  { name: "Institute of Chartered Accountants of India", city: "New Delhi", state: "Delhi", type: "Professional Institute" },
  { name: "National Law University AP", city: "Amaravati", state: "Andhra Pradesh", type: "NLU" },
  { name: "ICAR Indian Agricultural Research Institute", city: "New Delhi", state: "Delhi", type: "Agriculture Institute" },
  { name: "Tamil Nadu Agricultural University", city: "Coimbatore", state: "Tamil Nadu", type: "Agriculture University" },
  { name: "Punjab Agricultural University", city: "Ludhiana", state: "Punjab", type: "Agriculture University" },
  { name: "Kerala Agricultural University", city: "Thrissur", state: "Kerala", type: "Agriculture University" },
  { name: "Acharya NG Ranga Agricultural University", city: "Guntur", state: "Andhra Pradesh", type: "Agriculture University" },
  { name: "Dr YS Parmar University of Horticulture and Forestry", city: "Solan", state: "Himachal Pradesh", type: "Agriculture University" },
  { name: "GB Pant University of Agriculture and Technology", city: "Pantnagar", state: "Uttarakhand", type: "Agriculture University" },
  { name: "Rajendra Agricultural University", city: "Samastipur", state: "Bihar", type: "Agriculture University" },
  { name: "Orissa University of Agriculture and Technology", city: "Bhubaneswar", state: "Odisha", type: "Agriculture University" },
  { name: "Chaudhary Sarwan Kumar Himachal Pradesh Krishi Vishvavidyalaya", city: "Palampur", state: "Himachal Pradesh", type: "Agriculture University" },
  { name: "Jawaharlal Nehru Krishi Vishwa Vidyalaya", city: "Jabalpur", state: "Madhya Pradesh", type: "Agriculture University" },
  { name: "Marathwada Agricultural University", city: "Parbhani", state: "Maharashtra", type: "Agriculture University" },
  { name: "Dr Panjabrao Deshmukh Krishi Vidyapeeth", city: "Akola", state: "Maharashtra", type: "Agriculture University" },
  { name: "Junagadh Agricultural University", city: "Junagadh", state: "Gujarat", type: "Agriculture University" },
  { name: "Navsari Agricultural University", city: "Navsari", state: "Gujarat", type: "Agriculture University" },
  { name: "Anand Agricultural University", city: "Anand", state: "Gujarat", type: "Agriculture University" },
  { name: "Sardarkrushinagar Dantiwada Agricultural University", city: "Dantiwada", state: "Gujarat", type: "Agriculture University" },
  { name: "University of Agricultural Sciences Bangalore", city: "Bangalore", state: "Karnataka", type: "Agriculture University" },
  { name: "University of Agricultural Sciences Dharwad", city: "Dharwad", state: "Karnataka", type: "Agriculture University" },
  { name: "University of Horticultural Sciences Bagalkot", city: "Bagalkot", state: "Karnataka", type: "Agriculture University" },
  { name: "Bidhan Chandra Krishi Viswavidyalaya", city: "Nadia", state: "West Bengal", type: "Agriculture University" },
  { name: "Assam Agricultural University", city: "Jorhat", state: "Assam", type: "Agriculture University" },
  { name: "Chandra Shekhar Azad University of Agriculture and Technology", city: "Kanpur", state: "Uttar Pradesh", type: "Agriculture University" },
  { name: "Sardar Vallabhbhai Patel University of Agriculture and Technology", city: "Meerut", state: "Uttar Pradesh", type: "Agriculture University" },
  { name: "National Dairy Research Institute", city: "Karnal", state: "Haryana", type: "Research Institute" },
  { name: "CCS Haryana Agricultural University", city: "Hisar", state: "Haryana", type: "Agriculture University" },
  { name: "Rajasthan University of Veterinary and Animal Sciences", city: "Bikaner", state: "Rajasthan", type: "Veterinary University" },
  { name: "Maharashtra Animal and Fishery Sciences University", city: "Nagpur", state: "Maharashtra", type: "Veterinary University" },
  { name: "West Bengal University of Animal and Fishery Sciences", city: "Kolkata", state: "West Bengal", type: "Veterinary University" },
  { name: "Indira Gandhi National Tribal University", city: "Amarkantak", state: "Madhya Pradesh", type: "Central University" },
  { name: "Mahatma Gandhi Kashi Vidyapith", city: "Varanasi", state: "Uttar Pradesh", type: "State University" },
  { name: "Sampurnanand Sanskrit Vishwavidyalaya", city: "Varanasi", state: "Uttar Pradesh", type: "State University" },
  { name: "Dr APJ Abdul Kalam Technical University", city: "Lucknow", state: "Uttar Pradesh", type: "State University" },
  { name: "Madan Mohan Malaviya University of Technology", city: "Gorakhpur", state: "Uttar Pradesh", type: "State University" },
  { name: "King Georges Medical University Lucknow", city: "Lucknow", state: "Uttar Pradesh", type: "Medical University" },
  { name: "UP University of Medical Sciences", city: "Saifai", state: "Uttar Pradesh", type: "Medical University" },
  { name: "Maharashtra University of Health Sciences", city: "Nashik", state: "Maharashtra", type: "Medical University" },
  { name: "Kerala University of Health Sciences", city: "Thrissur", state: "Kerala", type: "Medical University" },
  { name: "Tamil Nadu Dr MGR Medical University", city: "Chennai", state: "Tamil Nadu", type: "Medical University" },
  { name: "Rajiv Gandhi University of Health Sciences", city: "Bangalore", state: "Karnataka", type: "Medical University" },
  { name: "Kaloji Narayana Rao University of Health Sciences", city: "Warangal", state: "Telangana", type: "Medical University" },
  { name: "Dr NTR University of Health Sciences", city: "Vijayawada", state: "Andhra Pradesh", type: "Medical University" },
  { name: "Baba Farid University of Health Sciences", city: "Faridkot", state: "Punjab", type: "Medical University" },
  { name: "Pt BD Sharma University of Health Sciences", city: "Rohtak", state: "Haryana", type: "Medical University" },
  { name: "West Bengal University of Health Sciences", city: "Kolkata", state: "West Bengal", type: "Medical University" },
  { name: "Sher-e-Kashmir University of Agricultural Sciences and Technology Jammu", city: "Jammu", state: "Jammu and Kashmir", type: "Agriculture University" },
  { name: "Sher-e-Kashmir University of Agricultural Sciences and Technology Kashmir", city: "Srinagar", state: "Jammu and Kashmir", type: "Agriculture University" },
  { name: "Central University of Andhra Pradesh", city: "Anantapur", state: "Andhra Pradesh", type: "Central University" },
  { name: "Dr Bhimrao Ambedkar University Agra", city: "Agra", state: "Uttar Pradesh", type: "State University" },
  { name: "Chatrapati Shahu Ji Maharaj University", city: "Kanpur", state: "Uttar Pradesh", type: "State University" },
  { name: "Jananayak Chandrashekhar University", city: "Ballia", state: "Uttar Pradesh", type: "State University" },
  { name: "Khwaja Moinuddin Chishti Language University", city: "Lucknow", state: "Uttar Pradesh", type: "State University" },
  { name: "Professor Rajendra Singh Rajju Bhaiya University", city: "Prayagraj", state: "Uttar Pradesh", type: "State University" },
  { name: "Raja Mahendra Pratap Singh State University", city: "Aligarh", state: "Uttar Pradesh", type: "State University" },
  { name: "Sido Kanhu Murmu University", city: "Dumka", state: "Jharkhand", type: "State University" },
  { name: "Kolhan University", city: "Chaibasa", state: "Jharkhand", type: "State University" },
  { name: "Vinoba Bhave University", city: "Hazaribag", state: "Jharkhand", type: "State University" },
  { name: "Nilamber Pitamber University", city: "Medininagar", state: "Jharkhand", type: "State University" },
  { name: "Fakir Mohan University", city: "Balasore", state: "Odisha", type: "State University" },
  { name: "Khallikote University", city: "Berhampur", state: "Odisha", type: "State University" },
  { name: "Maharaja Sriram Chandra Bhanjdeo University", city: "Baripada", state: "Odisha", type: "State University" },
  { name: "Gangadhar Meher University", city: "Sambalpur", state: "Odisha", type: "State University" },
  { name: "Rama Devi Womens University", city: "Bhubaneswar", state: "Odisha", type: "State University" },
  { name: "Cooch Behar Panchanan Barma University", city: "Cooch Behar", state: "West Bengal", type: "State University" },
  { name: "Kazi Nazrul University", city: "Asansol", state: "West Bengal", type: "State University" },
  { name: "Rani Rashmoni Green University", city: "Narayanpur", state: "West Bengal", type: "State University" },
  { name: "Aliah University", city: "Kolkata", state: "West Bengal", type: "State University" },
  { name: "Diamond Harbour Womens University", city: "Diamond Harbour", state: "West Bengal", type: "State University" },
  { name: "Rabindra Bharati University", city: "Kolkata", state: "West Bengal", type: "State University" },
  { name: "Maulana Abul Kalam Azad University of Technology", city: "Kolkata", state: "West Bengal", type: "State University" },
  { name: "Dr Shyama Prasad Mukherjee University", city: "Ranchi", state: "Jharkhand", type: "State University" },
  { name: "Jharkhand Raksha Shakti University", city: "Ranchi", state: "Jharkhand", type: "State University" },
  { name: "Birsa Agricultural University", city: "Ranchi", state: "Jharkhand", type: "Agriculture University" },
  { name: "Indira Kala Sangeet Vishwavidyalaya", city: "Khairgarh", state: "Chhattisgarh", type: "State University" },
  { name: "Bastar Vishwavidyalaya", city: "Jagdalpur", state: "Chhattisgarh", type: "State University" },
  { name: "Atal Bihari Vajpayee Vishwavidyalaya", city: "Bilaspur", state: "Chhattisgarh", type: "State University" },
  { name: "Chhattisgarh Swami Vivekanand Technical University", city: "Bhilai", state: "Chhattisgarh", type: "State University" },
  { name: "Maharaja Ganga Singh University", city: "Bikaner", state: "Rajasthan", type: "State University" },
  { name: "Maharaja Surajmal Brij University", city: "Bharatpur", state: "Rajasthan", type: "State University" },
  { name: "Matsya University", city: "Alwar", state: "Rajasthan", type: "State University" },
  { name: "Rajasthan Technical University", city: "Kota", state: "Rajasthan", type: "State University" },
  { name: "Vardhman Mahaveer Open University", city: "Kota", state: "Rajasthan", type: "State University" },
  { name: "MDS University", city: "Ajmer", state: "Rajasthan", type: "State University" },
  { name: "Shekhawati University", city: "Sikar", state: "Rajasthan", type: "State University" },
  { name: "Baba Mastnath University", city: "Rohtak", state: "Haryana", type: "Private University" },
  { name: "BPS Mahila Vishwavidyalaya", city: "Sonipat", state: "Haryana", type: "State University" },
  { name: "Chaudhary Ranbir Singh University", city: "Jind", state: "Haryana", type: "State University" },
  { name: "Deenbandhu Chhotu Ram University of Science and Technology", city: "Murthal", state: "Haryana", type: "State University" },
  { name: "Guru Jambheshwar University of Science and Technology", city: "Hisar", state: "Haryana", type: "State University" },
  { name: "Indira Gandhi University Meerpur", city: "Rewari", state: "Haryana", type: "State University" },
  { name: "Chaudhary Bansi Lal University", city: "Bhiwani", state: "Haryana", type: "State University" },
  { name: "Shri Vishwakarma Skill University", city: "Gurugram", state: "Haryana", type: "State University" },
  { name: "Baba Ghulam Shah Badshah University", city: "Rajouri", state: "Jammu and Kashmir", type: "State University" },
  { name: "Islamic University of Science and Technology", city: "Awantipora", state: "Jammu and Kashmir", type: "State University" },
  { name: "Cluster University Jammu", city: "Jammu", state: "Jammu and Kashmir", type: "State University" },
  { name: "Cluster University Srinagar", city: "Srinagar", state: "Jammu and Kashmir", type: "State University" },
];
