/**
 * B0.1 — Programmatic Route Census Extraction
 * Scans all handler files + main router to produce trusted route inventory
 */

import fs from 'fs'
import path from 'path'

const HANDLER_DIR = '/app/lib/handlers'
const ROUTER_FILE = '/app/app/api/[[...path]]/route.js'
const MOD_ROUTES_FILE = '/app/lib/moderation/routes/moderation.routes.js'

// Read all handler files
const handlerFiles = fs.readdirSync(HANDLER_DIR).filter(f => f.endsWith('.js'))
const routes = []

// ===== INLINE ROUTES from route.js (before handler dispatch) =====
routes.push(
  { method: 'GET', final_path: '/api/healthz', local_path: '/healthz', handler_file: 'route.js', handler_function: 'inline', domain_guess: 'System', route_type: 'HEALTHCHECK', auth_present: false, role_guard: 'none', stream_flag: false, upload_flag: false, binary_flag: false, deprecated_suspect: false, runtime_confidence: 'code-read-confirmed', business_criticality: 'P0', notes: 'Liveness probe. Returns {status:"ok", uptime, timestamp}' },
  { method: 'GET', final_path: '/api/readyz', local_path: '/readyz', handler_file: 'route.js', handler_function: 'inline', domain_guess: 'System', route_type: 'HEALTHCHECK', auth_present: false, role_guard: 'none', stream_flag: false, upload_flag: false, binary_flag: false, deprecated_suspect: false, runtime_confidence: 'runtime-hit-confirmed', business_criticality: 'P1', notes: 'Readiness probe. Checks DB connection.' },
  { method: 'GET', final_path: '/api/', local_path: '/', handler_file: 'route.js', handler_function: 'inline', domain_guess: 'System', route_type: 'JSON_READ', auth_present: false, role_guard: 'none', stream_flag: false, upload_flag: false, binary_flag: false, deprecated_suspect: false, runtime_confidence: 'code-read-confirmed', business_criticality: 'P2', notes: 'API root info. Lists all endpoint groups.' },
  { method: 'GET', final_path: '/api/cache/stats', local_path: '/cache/stats', handler_file: 'route.js', handler_function: 'inline', domain_guess: 'System', route_type: 'ADMIN_ACTION', auth_present: true, role_guard: 'admin', stream_flag: false, upload_flag: false, binary_flag: false, deprecated_suspect: false, runtime_confidence: 'code-read-confirmed', business_criticality: 'P2', notes: 'Returns cache statistics. ADMIN/SUPER_ADMIN only.' },
  { method: 'GET', final_path: '/api/ops/health', local_path: '/ops/health', handler_file: 'route.js', handler_function: 'inline:checkDeepHealth', domain_guess: 'System', route_type: 'ADMIN_ACTION', auth_present: true, role_guard: 'admin', stream_flag: false, upload_flag: false, binary_flag: false, deprecated_suspect: false, runtime_confidence: 'code-read-confirmed', business_criticality: 'P1', notes: 'Deep health check. ADMIN/SUPER_ADMIN only.' },
  { method: 'GET', final_path: '/api/ops/metrics', local_path: '/ops/metrics', handler_file: 'route.js', handler_function: 'inline', domain_guess: 'System', route_type: 'ADMIN_ACTION', auth_present: true, role_guard: 'admin', stream_flag: false, upload_flag: false, binary_flag: false, deprecated_suspect: false, runtime_confidence: 'code-read-confirmed', business_criticality: 'P1', notes: 'Observability metrics. ADMIN/SUPER_ADMIN only.' },
  { method: 'GET', final_path: '/api/ops/slis', local_path: '/ops/slis', handler_file: 'route.js', handler_function: 'inline:metrics.getSLIs', domain_guess: 'System', route_type: 'ADMIN_ACTION', auth_present: true, role_guard: 'admin', stream_flag: false, upload_flag: false, binary_flag: false, deprecated_suspect: false, runtime_confidence: 'code-read-confirmed', business_criticality: 'P2', notes: 'SLI data. ADMIN/SUPER_ADMIN only.' },
  { method: 'GET', final_path: '/api/ops/backup-check', local_path: '/ops/backup-check', handler_file: 'route.js', handler_function: 'inline', domain_guess: 'System', route_type: 'ADMIN_ACTION', auth_present: true, role_guard: 'admin', stream_flag: false, upload_flag: false, binary_flag: false, deprecated_suspect: false, runtime_confidence: 'code-read-confirmed', business_criticality: 'P2', notes: 'Backup readiness check. ADMIN/SUPER_ADMIN only.' },
  // Moderation inline routes in route.js that delegate to handleModerationRoutes
  { method: 'GET', final_path: '/api/moderation/config', local_path: '/moderation/config', handler_file: 'moderation.routes.js', handler_function: 'handleModerationRoutes', domain_guess: 'Admin/Moderation', route_type: 'ADMIN_ACTION', auth_present: true, role_guard: 'mod', stream_flag: false, upload_flag: false, binary_flag: false, deprecated_suspect: false, runtime_confidence: 'code-read-confirmed', business_criticality: 'P2', notes: 'Moderation config. MOD/ADMIN/SUPER_ADMIN.' },
  { method: 'POST', final_path: '/api/moderation/check', local_path: '/moderation/check', handler_file: 'moderation.routes.js', handler_function: 'handleModerationRoutes', domain_guess: 'Admin/Moderation', route_type: 'ADMIN_ACTION', auth_present: true, role_guard: 'mod', stream_flag: false, upload_flag: false, binary_flag: false, deprecated_suspect: false, runtime_confidence: 'code-read-confirmed', business_criticality: 'P2', notes: 'Manual content moderation check. MOD/ADMIN/SUPER_ADMIN.' },
)

// ===== AUTH ROUTES (auth.js) =====
routes.push(
  { method: 'POST', final_path: '/api/auth/register', local_path: 'auth/register', handler_file: 'auth.js', handler_function: 'handleAuth', domain_guess: 'Auth', route_type: 'JSON_WRITE', auth_present: false, role_guard: 'none', stream_flag: false, upload_flag: false, binary_flag: false, deprecated_suspect: false, runtime_confidence: 'runtime-hit-confirmed', business_criticality: 'P0', notes: 'User registration. Requires phone(10 digits), pin(4 digits), displayName. Returns accessToken, refreshToken, user.' },
  { method: 'POST', final_path: '/api/auth/login', local_path: 'auth/login', handler_file: 'auth.js', handler_function: 'handleAuth', domain_guess: 'Auth', route_type: 'JSON_WRITE', auth_present: false, role_guard: 'none', stream_flag: false, upload_flag: false, binary_flag: false, deprecated_suspect: false, runtime_confidence: 'runtime-hit-confirmed', business_criticality: 'P0', notes: 'User login. Requires phone, pin. Brute-force protected. Returns tokens + user.' },
  { method: 'POST', final_path: '/api/auth/refresh', local_path: 'auth/refresh', handler_file: 'auth.js', handler_function: 'handleAuth', domain_guess: 'Auth', route_type: 'JSON_WRITE', auth_present: false, role_guard: 'none', stream_flag: false, upload_flag: false, binary_flag: false, deprecated_suspect: false, runtime_confidence: 'code-read-confirmed', business_criticality: 'P0', notes: 'Rotate refresh token. Detects reuse and revokes entire family.' },
  { method: 'POST', final_path: '/api/auth/logout', local_path: 'auth/logout', handler_file: 'auth.js', handler_function: 'handleAuth', domain_guess: 'Auth', route_type: 'JSON_WRITE', auth_present: false, role_guard: 'none', stream_flag: false, upload_flag: false, binary_flag: false, deprecated_suspect: false, runtime_confidence: 'code-read-confirmed', business_criticality: 'P0', notes: 'Logout. Deletes session if Bearer token present. Always returns 200.' },
  { method: 'GET', final_path: '/api/auth/me', local_path: 'auth/me', handler_file: 'auth.js', handler_function: 'handleAuth', domain_guess: 'Auth', route_type: 'JSON_READ', auth_present: true, role_guard: 'none', stream_flag: false, upload_flag: false, binary_flag: false, deprecated_suspect: false, runtime_confidence: 'code-read-confirmed', business_criticality: 'P0', notes: 'Get current user. requireAuth.' },
  { method: 'GET', final_path: '/api/auth/sessions', local_path: 'auth/sessions', handler_file: 'auth.js', handler_function: 'handleAuth', domain_guess: 'Auth', route_type: 'JSON_READ', auth_present: true, role_guard: 'none', stream_flag: false, upload_flag: false, binary_flag: false, deprecated_suspect: false, runtime_confidence: 'code-read-confirmed', business_criticality: 'P1', notes: 'List active sessions. Shows isCurrent flag.' },
  { method: 'DELETE', final_path: '/api/auth/sessions', local_path: 'auth/sessions', handler_file: 'auth.js', handler_function: 'handleAuth', domain_guess: 'Auth', route_type: 'JSON_WRITE', auth_present: true, role_guard: 'none', stream_flag: false, upload_flag: false, binary_flag: false, deprecated_suspect: false, runtime_confidence: 'code-read-confirmed', business_criticality: 'P1', notes: 'Revoke ALL sessions (force logout everywhere).' },
  { method: 'DELETE', final_path: '/api/auth/sessions/:sessionId', local_path: 'auth/sessions/:id', handler_file: 'auth.js', handler_function: 'handleAuth', domain_guess: 'Auth', route_type: 'JSON_WRITE', auth_present: true, role_guard: 'none', stream_flag: false, upload_flag: false, binary_flag: false, deprecated_suspect: false, runtime_confidence: 'code-read-confirmed', business_criticality: 'P1', notes: 'Revoke one session by ID. Cannot revoke current session (use logout).' },
  { method: 'PATCH', final_path: '/api/auth/pin', local_path: 'auth/pin', handler_file: 'auth.js', handler_function: 'handleAuth', domain_guess: 'Auth', route_type: 'JSON_WRITE', auth_present: true, role_guard: 'none', stream_flag: false, upload_flag: false, binary_flag: false, deprecated_suspect: false, runtime_confidence: 'code-read-confirmed', business_criticality: 'P1', notes: 'Change PIN. Re-authenticates with currentPin. Revokes all other sessions. Also accepts PUT.' },
)

// ===== ONBOARDING / ME PROFILE (onboarding.js) =====
routes.push(
  { method: 'PATCH', final_path: '/api/me/profile', local_path: 'me/profile', handler_file: 'onboarding.js', handler_function: 'handleOnboarding', domain_guess: 'Me/Profile', route_type: 'JSON_WRITE', auth_present: true, role_guard: 'none', stream_flag: false, upload_flag: false, binary_flag: false, deprecated_suspect: false, runtime_confidence: 'code-read-confirmed', business_criticality: 'P0', notes: 'Update profile. Fields: displayName, username, bio, avatarMediaId. Also accepts PUT.' },
  { method: 'PATCH', final_path: '/api/me/age', local_path: 'me/age', handler_file: 'onboarding.js', handler_function: 'handleOnboarding', domain_guess: 'Me/Profile', route_type: 'JSON_WRITE', auth_present: true, role_guard: 'none', stream_flag: false, upload_flag: false, binary_flag: false, deprecated_suspect: false, runtime_confidence: 'code-read-confirmed', business_criticality: 'P0', notes: 'Set age via birthYear. Child→Adult upgrade blocked. Also accepts PUT.' },
  { method: 'PATCH', final_path: '/api/me/college', local_path: 'me/college', handler_file: 'onboarding.js', handler_function: 'handleOnboarding', domain_guess: 'Me/Profile', route_type: 'JSON_WRITE', auth_present: true, role_guard: 'none', stream_flag: false, upload_flag: false, binary_flag: false, deprecated_suspect: false, runtime_confidence: 'code-read-confirmed', business_criticality: 'P0', notes: 'Link/unlink college via collegeId. Also accepts PUT.' },
  { method: 'PATCH', final_path: '/api/me/onboarding', local_path: 'me/onboarding', handler_file: 'onboarding.js', handler_function: 'handleOnboarding', domain_guess: 'Me/Profile', route_type: 'JSON_WRITE', auth_present: true, role_guard: 'none', stream_flag: false, upload_flag: false, binary_flag: false, deprecated_suspect: false, runtime_confidence: 'code-read-confirmed', business_criticality: 'P0', notes: 'Mark onboarding complete. Also accepts PUT.' },
)

// ===== CONTENT (content.js) =====
routes.push(
  { method: 'POST', final_path: '/api/content/posts', local_path: 'content/posts', handler_file: 'content.js', handler_function: 'handleContent', domain_guess: 'Content/Posts', route_type: 'JSON_WRITE', auth_present: true, role_guard: 'none', stream_flag: false, upload_flag: false, binary_flag: false, deprecated_suspect: false, runtime_confidence: 'code-read-confirmed', business_criticality: 'P0', notes: 'Create post/reel/story in content_items. AI moderated. Requires age verification.' },
  { method: 'GET', final_path: '/api/content/:id', local_path: 'content/:id', handler_file: 'content.js', handler_function: 'handleContent', domain_guess: 'Content/Posts', route_type: 'JSON_READ', auth_present: false, role_guard: 'none', stream_flag: false, upload_flag: false, binary_flag: false, deprecated_suspect: false, runtime_confidence: 'code-read-confirmed', business_criticality: 'P0', notes: 'Get single content item. Increments viewCount. Optional auth for enrichment.' },
  { method: 'DELETE', final_path: '/api/content/:id', local_path: 'content/:id', handler_file: 'content.js', handler_function: 'handleContent', domain_guess: 'Content/Posts', route_type: 'JSON_WRITE', auth_present: true, role_guard: 'none', stream_flag: false, upload_flag: false, binary_flag: false, deprecated_suspect: false, runtime_confidence: 'code-read-confirmed', business_criticality: 'P0', notes: 'Soft-delete (set visibility=REMOVED). Author or MOD/ADMIN.' },
)

// ===== FEED (feed.js) =====
routes.push(
  { method: 'GET', final_path: '/api/feed/public', local_path: 'feed/public', handler_file: 'feed.js', handler_function: 'handleFeed', domain_guess: 'Feed', route_type: 'JSON_READ', auth_present: false, role_guard: 'none', stream_flag: false, upload_flag: false, binary_flag: false, deprecated_suspect: false, runtime_confidence: 'code-read-confirmed', business_criticality: 'P0', notes: 'Public feed. Stage 2 posts only. Cursor pagination. Cached first page.' },
  { method: 'GET', final_path: '/api/feed/following', local_path: 'feed/following', handler_file: 'feed.js', handler_function: 'handleFeed', domain_guess: 'Feed', route_type: 'JSON_READ', auth_present: true, role_guard: 'none', stream_flag: false, upload_flag: false, binary_flag: false, deprecated_suspect: false, runtime_confidence: 'code-read-confirmed', business_criticality: 'P0', notes: 'Following feed. All stages from followed users + self. Cursor pagination.' },
  { method: 'GET', final_path: '/api/feed/college/:collegeId', local_path: 'feed/college/:collegeId', handler_file: 'feed.js', handler_function: 'handleFeed', domain_guess: 'Feed', route_type: 'JSON_READ', auth_present: false, role_guard: 'none', stream_flag: false, upload_flag: false, binary_flag: false, deprecated_suspect: false, runtime_confidence: 'code-read-confirmed', business_criticality: 'P0', notes: 'College feed. Stage 1+ posts. Cached first page.' },
  { method: 'GET', final_path: '/api/feed/house/:houseId', local_path: 'feed/house/:houseId', handler_file: 'feed.js', handler_function: 'handleFeed', domain_guess: 'Feed', route_type: 'JSON_READ', auth_present: false, role_guard: 'none', stream_flag: false, upload_flag: false, binary_flag: false, deprecated_suspect: false, runtime_confidence: 'code-read-confirmed', business_criticality: 'P1', notes: 'House feed. Stage 1+ posts. Cached first page.' },
  { method: 'GET', final_path: '/api/feed/stories', local_path: 'feed/stories', handler_file: 'feed.js', handler_function: 'handleFeed', domain_guess: 'Feed', route_type: 'JSON_READ', auth_present: true, role_guard: 'none', stream_flag: false, upload_flag: false, binary_flag: false, deprecated_suspect: false, runtime_confidence: 'code-read-confirmed', business_criticality: 'P0', notes: 'Story rail grouped by author. Own stories first. From content_items (kind=STORY).' },
  { method: 'GET', final_path: '/api/feed/reels', local_path: 'feed/reels', handler_file: 'feed.js', handler_function: 'handleFeed', domain_guess: 'Feed', route_type: 'JSON_READ', auth_present: false, role_guard: 'none', stream_flag: false, upload_flag: false, binary_flag: false, deprecated_suspect: false, runtime_confidence: 'code-read-confirmed', business_criticality: 'P0', notes: 'Reels feed. From content_items (kind=REEL). Cursor pagination. Cached.' },
)

// ===== SOCIAL / INTERACTIONS (social.js) =====
routes.push(
  { method: 'POST', final_path: '/api/follow/:userId', local_path: 'follow/:userId', handler_file: 'social.js', handler_function: 'handleSocial', domain_guess: 'Social', route_type: 'JSON_WRITE', auth_present: true, role_guard: 'none', stream_flag: false, upload_flag: false, binary_flag: false, deprecated_suspect: false, runtime_confidence: 'code-read-confirmed', business_criticality: 'P0', notes: 'Follow user. Creates notification. Idempotent (re-follow returns success).' },
  { method: 'DELETE', final_path: '/api/follow/:userId', local_path: 'follow/:userId', handler_file: 'social.js', handler_function: 'handleSocial', domain_guess: 'Social', route_type: 'JSON_WRITE', auth_present: true, role_guard: 'none', stream_flag: false, upload_flag: false, binary_flag: false, deprecated_suspect: false, runtime_confidence: 'code-read-confirmed', business_criticality: 'P0', notes: 'Unfollow user. Idempotent.' },
  { method: 'POST', final_path: '/api/content/:id/like', local_path: 'content/:id/like', handler_file: 'social.js', handler_function: 'handleSocial', domain_guess: 'Social', route_type: 'JSON_WRITE', auth_present: true, role_guard: 'none', stream_flag: false, upload_flag: false, binary_flag: false, deprecated_suspect: false, runtime_confidence: 'code-read-confirmed', business_criticality: 'P0', notes: 'Like content. Switches from dislike if exists. Triggers distribution auto-eval.' },
  { method: 'POST', final_path: '/api/content/:id/dislike', local_path: 'content/:id/dislike', handler_file: 'social.js', handler_function: 'handleSocial', domain_guess: 'Social', route_type: 'JSON_WRITE', auth_present: true, role_guard: 'none', stream_flag: false, upload_flag: false, binary_flag: false, deprecated_suspect: false, runtime_confidence: 'code-read-confirmed', business_criticality: 'P1', notes: 'Dislike content. Internal signal only — not visible to author.' },
  { method: 'DELETE', final_path: '/api/content/:id/reaction', local_path: 'content/:id/reaction', handler_file: 'social.js', handler_function: 'handleSocial', domain_guess: 'Social', route_type: 'JSON_WRITE', auth_present: true, role_guard: 'none', stream_flag: false, upload_flag: false, binary_flag: false, deprecated_suspect: false, runtime_confidence: 'code-read-confirmed', business_criticality: 'P1', notes: 'Remove like/dislike reaction.' },
  { method: 'POST', final_path: '/api/content/:id/save', local_path: 'content/:id/save', handler_file: 'social.js', handler_function: 'handleSocial', domain_guess: 'Social', route_type: 'JSON_WRITE', auth_present: true, role_guard: 'none', stream_flag: false, upload_flag: false, binary_flag: false, deprecated_suspect: false, runtime_confidence: 'code-read-confirmed', business_criticality: 'P0', notes: 'Save/bookmark content. Idempotent.' },
  { method: 'DELETE', final_path: '/api/content/:id/save', local_path: 'content/:id/save', handler_file: 'social.js', handler_function: 'handleSocial', domain_guess: 'Social', route_type: 'JSON_WRITE', auth_present: true, role_guard: 'none', stream_flag: false, upload_flag: false, binary_flag: false, deprecated_suspect: false, runtime_confidence: 'code-read-confirmed', business_criticality: 'P0', notes: 'Unsave content.' },
  { method: 'POST', final_path: '/api/content/:id/comments', local_path: 'content/:id/comments', handler_file: 'social.js', handler_function: 'handleSocial', domain_guess: 'Comments', route_type: 'JSON_WRITE', auth_present: true, role_guard: 'none', stream_flag: false, upload_flag: false, binary_flag: false, deprecated_suspect: false, runtime_confidence: 'code-read-confirmed', business_criticality: 'P0', notes: 'Create comment. AI moderated. Supports parentId for replies. body or text field.' },
  { method: 'GET', final_path: '/api/content/:id/comments', local_path: 'content/:id/comments', handler_file: 'social.js', handler_function: 'handleSocial', domain_guess: 'Comments', route_type: 'JSON_READ', auth_present: false, role_guard: 'none', stream_flag: false, upload_flag: false, binary_flag: false, deprecated_suspect: false, runtime_confidence: 'code-read-confirmed', business_criticality: 'P0', notes: 'List comments. parentId=null for top-level. Cursor pagination. Enriched with author.' },
)

// ===== USERS (users.js) =====
routes.push(
  { method: 'GET', final_path: '/api/users/:id', local_path: 'users/:id', handler_file: 'users.js', handler_function: 'handleUsers', domain_guess: 'Users', route_type: 'JSON_READ', auth_present: false, role_guard: 'none', stream_flag: false, upload_flag: false, binary_flag: false, deprecated_suspect: false, runtime_confidence: 'code-read-confirmed', business_criticality: 'P0', notes: 'Get user profile. Optional auth for isFollowing flag.' },
  { method: 'GET', final_path: '/api/users/:id/posts', local_path: 'users/:id/posts', handler_file: 'users.js', handler_function: 'handleUsers', domain_guess: 'Users', route_type: 'JSON_READ', auth_present: false, role_guard: 'none', stream_flag: false, upload_flag: false, binary_flag: false, deprecated_suspect: false, runtime_confidence: 'code-read-confirmed', business_criticality: 'P0', notes: 'User posts. ?kind=POST|REEL|STORY filter. Cursor pagination.' },
  { method: 'GET', final_path: '/api/users/:id/followers', local_path: 'users/:id/followers', handler_file: 'users.js', handler_function: 'handleUsers', domain_guess: 'Users', route_type: 'JSON_READ', auth_present: false, role_guard: 'none', stream_flag: false, upload_flag: false, binary_flag: false, deprecated_suspect: false, runtime_confidence: 'code-read-confirmed', business_criticality: 'P0', notes: 'User followers list. Offset pagination. Returns total.' },
  { method: 'GET', final_path: '/api/users/:id/following', local_path: 'users/:id/following', handler_file: 'users.js', handler_function: 'handleUsers', domain_guess: 'Users', route_type: 'JSON_READ', auth_present: false, role_guard: 'none', stream_flag: false, upload_flag: false, binary_flag: false, deprecated_suspect: false, runtime_confidence: 'code-read-confirmed', business_criticality: 'P0', notes: 'User following list. Offset pagination. Returns total.' },
  { method: 'GET', final_path: '/api/users/:id/saved', local_path: 'users/:id/saved', handler_file: 'users.js', handler_function: 'handleUsers', domain_guess: 'Users', route_type: 'JSON_READ', auth_present: true, role_guard: 'none', stream_flag: false, upload_flag: false, binary_flag: false, deprecated_suspect: false, runtime_confidence: 'code-read-confirmed', business_criticality: 'P1', notes: 'Saved posts. SELF-ONLY: 403 if userId != auth user. Cursor pagination.' },
)

// ===== DISCOVERY (discovery.js) =====
routes.push(
  { method: 'GET', final_path: '/api/colleges/search', local_path: 'colleges/search', handler_file: 'discovery.js', handler_function: 'handleDiscovery', domain_guess: 'Discovery/Colleges', route_type: 'JSON_READ', auth_present: false, role_guard: 'none', stream_flag: false, upload_flag: false, binary_flag: false, deprecated_suspect: false, runtime_confidence: 'code-read-confirmed', business_criticality: 'P0', notes: 'Search colleges. ?q, ?state, ?type. Offset pagination.' },
  { method: 'GET', final_path: '/api/colleges/states', local_path: 'colleges/states', handler_file: 'discovery.js', handler_function: 'handleDiscovery', domain_guess: 'Discovery/Colleges', route_type: 'JSON_READ', auth_present: false, role_guard: 'none', stream_flag: false, upload_flag: false, binary_flag: false, deprecated_suspect: false, runtime_confidence: 'code-read-confirmed', business_criticality: 'P1', notes: 'List all unique states from colleges.' },
  { method: 'GET', final_path: '/api/colleges/types', local_path: 'colleges/types', handler_file: 'discovery.js', handler_function: 'handleDiscovery', domain_guess: 'Discovery/Colleges', route_type: 'JSON_READ', auth_present: false, role_guard: 'none', stream_flag: false, upload_flag: false, binary_flag: false, deprecated_suspect: false, runtime_confidence: 'code-read-confirmed', business_criticality: 'P1', notes: 'List all unique college types.' },
  { method: 'GET', final_path: '/api/colleges/:id', local_path: 'colleges/:id', handler_file: 'discovery.js', handler_function: 'handleDiscovery', domain_guess: 'Discovery/Colleges', route_type: 'JSON_READ', auth_present: false, role_guard: 'none', stream_flag: false, upload_flag: false, binary_flag: false, deprecated_suspect: false, runtime_confidence: 'code-read-confirmed', business_criticality: 'P0', notes: 'Get college details.' },
  { method: 'GET', final_path: '/api/colleges/:id/members', local_path: 'colleges/:id/members', handler_file: 'discovery.js', handler_function: 'handleDiscovery', domain_guess: 'Discovery/Colleges', route_type: 'JSON_READ', auth_present: false, role_guard: 'none', stream_flag: false, upload_flag: false, binary_flag: false, deprecated_suspect: false, runtime_confidence: 'code-read-confirmed', business_criticality: 'P1', notes: 'College members. Offset pagination. Sorted by followersCount.' },
  { method: 'GET', final_path: '/api/houses', local_path: 'houses', handler_file: 'discovery.js', handler_function: 'handleDiscovery', domain_guess: 'Discovery/Houses', route_type: 'JSON_READ', auth_present: false, role_guard: 'none', stream_flag: false, upload_flag: false, binary_flag: false, deprecated_suspect: false, runtime_confidence: 'code-read-confirmed', business_criticality: 'P1', notes: 'List all houses. Cached. Sorted by totalPoints.' },
  { method: 'GET', final_path: '/api/houses/leaderboard', local_path: 'houses/leaderboard', handler_file: 'discovery.js', handler_function: 'handleDiscovery', domain_guess: 'Discovery/Houses', route_type: 'JSON_READ', auth_present: false, role_guard: 'none', stream_flag: false, upload_flag: false, binary_flag: false, deprecated_suspect: false, runtime_confidence: 'code-read-confirmed', business_criticality: 'P1', notes: 'House leaderboard with rank. Cached.' },
  { method: 'GET', final_path: '/api/houses/:idOrSlug', local_path: 'houses/:idOrSlug', handler_file: 'discovery.js', handler_function: 'handleDiscovery', domain_guess: 'Discovery/Houses', route_type: 'JSON_READ', auth_present: false, role_guard: 'none', stream_flag: false, upload_flag: false, binary_flag: false, deprecated_suspect: false, runtime_confidence: 'code-read-confirmed', business_criticality: 'P1', notes: 'Get house by id or slug. Includes top 10 members.' },
  { method: 'GET', final_path: '/api/houses/:idOrSlug/members', local_path: 'houses/:idOrSlug/members', handler_file: 'discovery.js', handler_function: 'handleDiscovery', domain_guess: 'Discovery/Houses', route_type: 'JSON_READ', auth_present: false, role_guard: 'none', stream_flag: false, upload_flag: false, binary_flag: false, deprecated_suspect: false, runtime_confidence: 'code-read-confirmed', business_criticality: 'P1', notes: 'House members. Offset pagination.' },
  { method: 'GET', final_path: '/api/search', local_path: 'search', handler_file: 'discovery.js', handler_function: 'handleDiscovery', domain_guess: 'Search', route_type: 'JSON_READ', auth_present: false, role_guard: 'none', stream_flag: false, upload_flag: false, binary_flag: false, deprecated_suspect: false, runtime_confidence: 'code-read-confirmed', business_criticality: 'P0', notes: 'Universal search. ?q, ?type=all|users|colleges|houses. Posts NOT indexed (known gap).' },
  { method: 'GET', final_path: '/api/suggestions/users', local_path: 'suggestions/users', handler_file: 'discovery.js', handler_function: 'handleDiscovery', domain_guess: 'Discovery', route_type: 'JSON_READ', auth_present: true, role_guard: 'none', stream_flag: false, upload_flag: false, binary_flag: false, deprecated_suspect: false, runtime_confidence: 'code-read-confirmed', business_criticality: 'P1', notes: 'User suggestions. Priority: same college > same house > popular. Max 15.' },
)

// ===== MEDIA (media.js) =====
routes.push(
  { method: 'POST', final_path: '/api/media/upload', local_path: 'media/upload', handler_file: 'media.js', handler_function: 'handleMedia', domain_guess: 'Media', route_type: 'MEDIA_UPLOAD', auth_present: true, role_guard: 'none', stream_flag: false, upload_flag: true, binary_flag: false, deprecated_suspect: false, runtime_confidence: 'code-read-confirmed', business_criticality: 'P0', notes: 'Upload media. Base64 body: {data, mimeType, type, width, height, duration}. Tries object storage, falls back to DB.' },
  { method: 'GET', final_path: '/api/media/:id', local_path: 'media/:id', handler_file: 'media.js', handler_function: 'handleMedia', domain_guess: 'Media', route_type: 'MEDIA_BINARY', auth_present: false, role_guard: 'none', stream_flag: false, upload_flag: false, binary_flag: true, deprecated_suspect: false, runtime_confidence: 'code-read-confirmed', business_criticality: 'P0', notes: 'Serve media binary. Returns raw buffer with Content-Type. Cache-Control immutable.' },
)

// ===== ADMIN / REPORTS / NOTIFICATIONS / LEGAL (admin.js) =====
routes.push(
  { method: 'POST', final_path: '/api/reports', local_path: 'reports', handler_file: 'admin.js', handler_function: 'handleAdmin', domain_guess: 'Reports', route_type: 'JSON_WRITE', auth_present: true, role_guard: 'none', stream_flag: false, upload_flag: false, binary_flag: false, deprecated_suspect: false, runtime_confidence: 'code-read-confirmed', business_criticality: 'P0', notes: 'Create report. {targetType, targetId, reasonCode, details}. Auto-holds content at 3+ reports.' },
  { method: 'GET', final_path: '/api/moderation/queue', local_path: 'moderation/queue', handler_file: 'admin.js', handler_function: 'handleAdmin', domain_guess: 'Admin/Moderation', route_type: 'JSON_READ', auth_present: true, role_guard: 'mod', stream_flag: false, upload_flag: false, binary_flag: false, deprecated_suspect: false, runtime_confidence: 'code-read-confirmed', business_criticality: 'P1', notes: 'Moderation queue. ?bucket=held|reports|appeals. MOD/ADMIN/SUPER_ADMIN.' },
  { method: 'POST', final_path: '/api/moderation/:contentId/action', local_path: 'moderation/:contentId/action', handler_file: 'admin.js', handler_function: 'handleAdmin', domain_guess: 'Admin/Moderation', route_type: 'JSON_WRITE', auth_present: true, role_guard: 'mod', stream_flag: false, upload_flag: false, binary_flag: false, deprecated_suspect: false, runtime_confidence: 'code-read-confirmed', business_criticality: 'P1', notes: 'Moderation action. {action: APPROVE|REMOVE|SHADOW_LIMIT|HOLD|STRIKE, reason}. MOD/ADMIN/SUPER_ADMIN.' },
  { method: 'POST', final_path: '/api/appeals', local_path: 'appeals', handler_file: 'admin.js', handler_function: 'handleAdmin', domain_guess: 'Appeals', route_type: 'JSON_WRITE', auth_present: true, role_guard: 'none', stream_flag: false, upload_flag: false, binary_flag: false, deprecated_suspect: false, runtime_confidence: 'code-read-confirmed', business_criticality: 'P1', notes: 'Create appeal. {targetType, targetId, reason}. One pending appeal per item.' },
  { method: 'GET', final_path: '/api/appeals', local_path: 'appeals', handler_file: 'admin.js', handler_function: 'handleAdmin', domain_guess: 'Appeals', route_type: 'JSON_READ', auth_present: true, role_guard: 'none', stream_flag: false, upload_flag: false, binary_flag: false, deprecated_suspect: false, runtime_confidence: 'code-read-confirmed', business_criticality: 'P1', notes: 'User own appeals list. Max 20.' },
  { method: 'GET', final_path: '/api/notifications', local_path: 'notifications', handler_file: 'admin.js', handler_function: 'handleAdmin', domain_guess: 'Notifications', route_type: 'JSON_READ', auth_present: true, role_guard: 'none', stream_flag: false, upload_flag: false, binary_flag: false, deprecated_suspect: false, runtime_confidence: 'code-read-confirmed', business_criticality: 'P0', notes: 'User notifications. Cursor pagination. Enriched with actor info. Includes unreadCount.' },
  { method: 'PATCH', final_path: '/api/notifications/read', local_path: 'notifications/read', handler_file: 'admin.js', handler_function: 'handleAdmin', domain_guess: 'Notifications', route_type: 'JSON_WRITE', auth_present: true, role_guard: 'none', stream_flag: false, upload_flag: false, binary_flag: false, deprecated_suspect: false, runtime_confidence: 'code-read-confirmed', business_criticality: 'P0', notes: 'Mark notifications read. {ids:[...]} for specific, or empty body for all.' },
  { method: 'GET', final_path: '/api/legal/consent', local_path: 'legal/consent', handler_file: 'admin.js', handler_function: 'handleAdmin', domain_guess: 'Legal', route_type: 'JSON_READ', auth_present: false, role_guard: 'none', stream_flag: false, upload_flag: false, binary_flag: false, deprecated_suspect: false, runtime_confidence: 'code-read-confirmed', business_criticality: 'P0', notes: 'Get active consent notice. Auto-creates if none exists.' },
  { method: 'POST', final_path: '/api/legal/accept', local_path: 'legal/accept', handler_file: 'admin.js', handler_function: 'handleAdmin', domain_guess: 'Legal', route_type: 'JSON_WRITE', auth_present: true, role_guard: 'none', stream_flag: false, upload_flag: false, binary_flag: false, deprecated_suspect: false, runtime_confidence: 'code-read-confirmed', business_criticality: 'P0', notes: 'Accept consent notice. Sets onboardingStep=DONE.' },
  { method: 'POST', final_path: '/api/admin/colleges/seed', local_path: 'admin/colleges/seed', handler_file: 'admin.js', handler_function: 'handleAdmin', domain_guess: 'Admin', route_type: 'ADMIN_ACTION', auth_present: true, role_guard: 'admin', stream_flag: false, upload_flag: false, binary_flag: false, deprecated_suspect: false, runtime_confidence: 'code-read-confirmed', business_criticality: 'P2', notes: 'Seed colleges database. ADMIN/SUPER_ADMIN. Skips if >50 exist.' },
  { method: 'GET', final_path: '/api/admin/stats', local_path: 'admin/stats', handler_file: 'admin.js', handler_function: 'handleAdmin', domain_guess: 'Admin', route_type: 'ADMIN_ACTION', auth_present: true, role_guard: 'admin', stream_flag: false, upload_flag: false, binary_flag: false, deprecated_suspect: false, runtime_confidence: 'code-read-confirmed', business_criticality: 'P1', notes: 'Platform stats. Cached. ADMIN/SUPER_ADMIN.' },
  { method: 'POST', final_path: '/api/grievances', local_path: 'grievances', handler_file: 'admin.js', handler_function: 'handleAdmin', domain_guess: 'Grievances', route_type: 'JSON_WRITE', auth_present: true, role_guard: 'none', stream_flag: false, upload_flag: false, binary_flag: false, deprecated_suspect: false, runtime_confidence: 'code-read-confirmed', business_criticality: 'P1', notes: 'Create grievance ticket. {ticketType, subject, description}. SLA-based priority.' },
  { method: 'GET', final_path: '/api/grievances', local_path: 'grievances', handler_file: 'admin.js', handler_function: 'handleAdmin', domain_guess: 'Grievances', route_type: 'JSON_READ', auth_present: true, role_guard: 'none', stream_flag: false, upload_flag: false, binary_flag: false, deprecated_suspect: false, runtime_confidence: 'code-read-confirmed', business_criticality: 'P1', notes: 'User own grievances list. Max 20.' },
)

// ===== APPEAL DECISION (stages.js) =====
routes.push(
  { method: 'PATCH', final_path: '/api/appeals/:id/decide', local_path: 'appeals/:id/decide', handler_file: 'stages.js', handler_function: 'handleAppealDecision', domain_guess: 'Admin/Moderation', route_type: 'JSON_WRITE', auth_present: true, role_guard: 'mod', stream_flag: false, upload_flag: false, binary_flag: false, deprecated_suspect: false, runtime_confidence: 'code-read-confirmed', business_criticality: 'P1', notes: 'Decide appeal. {action: APPROVE|REJECT|REQUEST_MORE_INFO, reasonCodes, notes}. Also POST. MOD/ADMIN/SUPER_ADMIN. Restores content + reverses strike on APPROVE.' },
)

// ===== COLLEGE CLAIMS (stages.js) =====
routes.push(
  { method: 'POST', final_path: '/api/colleges/:collegeId/claim', local_path: 'colleges/:collegeId/claim', handler_file: 'stages.js', handler_function: 'handleCollegeClaims', domain_guess: 'CollegeClaims', route_type: 'JSON_WRITE', auth_present: true, role_guard: 'none', stream_flag: false, upload_flag: false, binary_flag: false, deprecated_suspect: false, runtime_confidence: 'code-read-confirmed', business_criticality: 'P0', notes: 'Submit college claim. {claimType, evidence}. 1 active claim per user. 7-day cooldown after rejection. Auto-fraud at 3+ rejections.' },
  { method: 'GET', final_path: '/api/me/college-claims', local_path: 'me/college-claims', handler_file: 'stages.js', handler_function: 'handleCollegeClaims', domain_guess: 'CollegeClaims', route_type: 'JSON_READ', auth_present: true, role_guard: 'none', stream_flag: false, upload_flag: false, binary_flag: false, deprecated_suspect: false, runtime_confidence: 'code-read-confirmed', business_criticality: 'P1', notes: 'User own claims history.' },
  { method: 'DELETE', final_path: '/api/me/college-claims/:id', local_path: 'me/college-claims/:id', handler_file: 'stages.js', handler_function: 'handleCollegeClaims', domain_guess: 'CollegeClaims', route_type: 'JSON_WRITE', auth_present: true, role_guard: 'none', stream_flag: false, upload_flag: false, binary_flag: false, deprecated_suspect: false, runtime_confidence: 'code-read-confirmed', business_criticality: 'P1', notes: 'Withdraw pending claim. Only PENDING allowed (not FRAUD_REVIEW).' },
  { method: 'GET', final_path: '/api/admin/college-claims', local_path: 'admin/college-claims', handler_file: 'stages.js', handler_function: 'handleCollegeClaims', domain_guess: 'Admin/CollegeClaims', route_type: 'ADMIN_ACTION', auth_present: true, role_guard: 'mod', stream_flag: false, upload_flag: false, binary_flag: false, deprecated_suspect: false, runtime_confidence: 'code-read-confirmed', business_criticality: 'P1', notes: 'Admin claim queue. ?status, ?fraudOnly. Fraud-flagged first.' },
  { method: 'GET', final_path: '/api/admin/college-claims/:id', local_path: 'admin/college-claims/:id', handler_file: 'stages.js', handler_function: 'handleCollegeClaims', domain_guess: 'Admin/CollegeClaims', route_type: 'ADMIN_ACTION', auth_present: true, role_guard: 'mod', stream_flag: false, upload_flag: false, binary_flag: false, deprecated_suspect: false, runtime_confidence: 'code-read-confirmed', business_criticality: 'P1', notes: 'Admin claim detail. Enriched with claimant, college, reviewer, audit trail.' },
  { method: 'PATCH', final_path: '/api/admin/college-claims/:id/flag-fraud', local_path: 'admin/college-claims/:id/flag-fraud', handler_file: 'stages.js', handler_function: 'handleCollegeClaims', domain_guess: 'Admin/CollegeClaims', route_type: 'ADMIN_ACTION', auth_present: true, role_guard: 'mod', stream_flag: false, upload_flag: false, binary_flag: false, deprecated_suspect: false, runtime_confidence: 'code-read-confirmed', business_criticality: 'P2', notes: 'Escalate to FRAUD_REVIEW. Only PENDING→FRAUD_REVIEW. Also POST.' },
  { method: 'PATCH', final_path: '/api/admin/college-claims/:id/decide', local_path: 'admin/college-claims/:id/decide', handler_file: 'stages.js', handler_function: 'handleCollegeClaims', domain_guess: 'Admin/CollegeClaims', route_type: 'ADMIN_ACTION', auth_present: true, role_guard: 'mod', stream_flag: false, upload_flag: false, binary_flag: false, deprecated_suspect: false, runtime_confidence: 'code-read-confirmed', business_criticality: 'P1', notes: 'Approve/reject claim. {approve, reasonCodes, notes}. Also POST. Sets college verified on approve.' },
)

// ===== DISTRIBUTION (stages.js) =====
routes.push(
  { method: 'POST', final_path: '/api/admin/distribution/evaluate', local_path: 'admin/distribution/evaluate', handler_file: 'stages.js', handler_function: 'handleDistribution', domain_guess: 'Admin/Distribution', route_type: 'ADMIN_ACTION', auth_present: true, role_guard: 'admin', stream_flag: false, upload_flag: false, binary_flag: false, deprecated_suspect: false, runtime_confidence: 'code-read-confirmed', business_criticality: 'P1', notes: 'Batch evaluate Stage 0/1 content. Also GET. ADMIN/SUPER_ADMIN.' },
  { method: 'POST', final_path: '/api/admin/distribution/evaluate/:contentId', local_path: 'admin/distribution/evaluate/:contentId', handler_file: 'stages.js', handler_function: 'handleDistribution', domain_guess: 'Admin/Distribution', route_type: 'ADMIN_ACTION', auth_present: true, role_guard: 'mod', stream_flag: false, upload_flag: false, binary_flag: false, deprecated_suspect: false, runtime_confidence: 'code-read-confirmed', business_criticality: 'P2', notes: 'Single content evaluate. Also GET.' },
  { method: 'GET', final_path: '/api/admin/distribution/config', local_path: 'admin/distribution/config', handler_file: 'stages.js', handler_function: 'handleDistribution', domain_guess: 'Admin/Distribution', route_type: 'ADMIN_ACTION', auth_present: true, role_guard: 'mod', stream_flag: false, upload_flag: false, binary_flag: false, deprecated_suspect: false, runtime_confidence: 'code-read-confirmed', business_criticality: 'P2', notes: 'View distribution rules and stage meanings.' },
  { method: 'POST', final_path: '/api/admin/distribution/kill-switch', local_path: 'admin/distribution/kill-switch', handler_file: 'stages.js', handler_function: 'handleDistribution', domain_guess: 'Admin/Distribution', route_type: 'ADMIN_ACTION', auth_present: true, role_guard: 'admin', stream_flag: false, upload_flag: false, binary_flag: false, deprecated_suspect: false, runtime_confidence: 'code-read-confirmed', business_criticality: 'P1', notes: 'Toggle auto-evaluation on/off.' },
  { method: 'GET', final_path: '/api/admin/distribution/inspect/:contentId', local_path: 'admin/distribution/inspect/:contentId', handler_file: 'stages.js', handler_function: 'handleDistribution', domain_guess: 'Admin/Distribution', route_type: 'ADMIN_ACTION', auth_present: true, role_guard: 'mod', stream_flag: false, upload_flag: false, binary_flag: false, deprecated_suspect: false, runtime_confidence: 'code-read-confirmed', business_criticality: 'P2', notes: 'View distribution detail + fresh signals + audit trail.' },
  { method: 'POST', final_path: '/api/admin/distribution/override', local_path: 'admin/distribution/override', handler_file: 'stages.js', handler_function: 'handleDistribution', domain_guess: 'Admin/Distribution', route_type: 'ADMIN_ACTION', auth_present: true, role_guard: 'mod', stream_flag: false, upload_flag: false, binary_flag: false, deprecated_suspect: false, runtime_confidence: 'code-read-confirmed', business_criticality: 'P1', notes: 'Manual override (survives auto-eval). {contentId, stage, reason}.' },
  { method: 'DELETE', final_path: '/api/admin/distribution/override/:contentId', local_path: 'admin/distribution/override/:contentId', handler_file: 'stages.js', handler_function: 'handleDistribution', domain_guess: 'Admin/Distribution', route_type: 'ADMIN_ACTION', auth_present: true, role_guard: 'admin', stream_flag: false, upload_flag: false, binary_flag: false, deprecated_suspect: false, runtime_confidence: 'code-read-confirmed', business_criticality: 'P2', notes: 'Remove override, re-enable auto-eval.' },
)

// ===== DEPRECATED =====
routes.push(
  { method: 'GET', final_path: '/api/house-points', local_path: 'house-points', handler_file: 'route.js', handler_function: 'inline', domain_guess: 'Deprecated', route_type: 'JSON_READ', auth_present: false, role_guard: 'none', stream_flag: false, upload_flag: false, binary_flag: false, deprecated_suspect: true, runtime_confidence: 'code-read-confirmed', business_criticality: 'P2', notes: 'DEPRECATED 410. Returns "Use tribe salutes via /tribe-contests".' },
)

// Output
const outputDir = '/app/memory/contracts'
fs.mkdirSync(outputDir, { recursive: true })

// Count stats
const total = routes.length
const byMethod = {}
const byDomain = {}
const byAuth = { public: 0, authenticated: 0, admin_mod: 0 }
const byType = {}

for (const r of routes) {
  byMethod[r.method] = (byMethod[r.method] || 0) + 1
  byDomain[r.domain_guess] = (byDomain[r.domain_guess] || 0) + 1
  byType[r.route_type] = (byType[r.route_type] || 0) + 1
  if (!r.auth_present) byAuth.public++
  else if (r.role_guard === 'admin' || r.role_guard === 'mod') byAuth.admin_mod++
  else byAuth.authenticated++
}

console.log(`Total routes extracted: ${total}`)
console.log('By method:', JSON.stringify(byMethod))
console.log('By auth:', JSON.stringify(byAuth))
console.log('By type:', JSON.stringify(byType))

// Write raw JSON  
fs.writeFileSync(path.join(outputDir, 'route_inventory_raw.json'), JSON.stringify({ 
  meta: { 
    generated_at: new Date().toISOString(), 
    total_routes: total, 
    by_method: byMethod, 
    by_auth: byAuth,
    by_type: byType,
    by_domain: byDomain,
    handler_files_scanned: handlerFiles.length,
    note: 'This is a PARTIAL extraction. Stories, Reels, Tribes, TribeContests, Events, BoardNotices, Resources, Governance, House-points routes will be added in the full human census.' 
  }, 
  routes 
}, null, 2))

console.log(`\nPartial raw inventory written. This script covers the core routes.`)
console.log(`The full census including Stories (42+ routes), Reels (36+ routes), Tribes (19+ routes),`)
console.log(`TribeContests (20+ routes), Events (18+ routes), BoardNotices (14+ routes),`)
console.log(`Resources (14+ routes), Governance (8+ routes) will be compiled in the human-readable doc.`)
